import { AchievementType } from "../Cliker2";

export const AlchemyLabAchievement: AchievementType[] = [
  {
    id: 285,
    name: "Transmutation",
    description: "Have 1 alchemy lab",
    condition: 1,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 286,
    name: "Transmogrification",
    description: "Have 50 alchemy labs",
    condition: 50,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 287,
    name: "Gold member",
    description: "Have 100 alchemy labs",
    condition: 100,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 288,
    name: "Gild wars",
    description: "Have 150 alchemy labs",
    condition: 150,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 289,
    name: "The secrets of the universe",
    description: "Have 200 alchemy labs",
    condition: 200,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 290,
    name: "The work of a lifetime",
    description: "Have 250 alchemy labs",
    condition: 250,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 291,
    name: "Gold, Jerry! Gold!",
    description: "Have 300 alchemy labs",
    condition: 300,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 292,
    name: "All that glitters is gold",
    description: "Have 350 alchemy labs",
    condition: 350,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 293,
    name: "Worth its weight in lead",
    description: "Have 400 alchemy labs",
    condition: 400,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 294,
    name: "Don't get used to yourself, you're gonna have to change",
    description: "Have 450 alchemy labs",
    condition: 450,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 295,
    name: "We could all use a little change",
    description: "Have 500 alchemy labs",
    condition: 500,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 296,
    name: "Just a phase",
    description: "Have 550 alchemy labs",
    condition: 550,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 297,
    name: "Bad chemistry",
    description: "Have 600 alchemy labs",
    condition: 600,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 298,
    name: "Metalic taste",
    description: "Have 650 alchemy labs",
    condition: 650,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 299,
    name: "Sugar, spice and everything nice",
    description: "Have 700 alchemy labs",
    condition: 700,
    achievementType: "Having",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 300,
    name: "Magnum Opus",
    description: "Make 1 sextillion cookies just from alchemy labs.",
    condition: 1e21,
    achievementType: "Baking",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 301,
    name: "The Aureate",
    description: "Make 10 octillion cookies just from alchemy labs.",
    condition: 1e28,
    achievementType: "Baking",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 302,
    name: "I've got the Midas touch",
    description: "Make 100 decillion cookies just from alchemy labs.",
    condition: 1e35,
    achievementType: "Baking",
    type: "alchemyLab",
    acquired: false,
  },
  {
    id: 303,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "alchemyLab",
    acquired: false,
  },
];
