import { AchievementType } from "../Cliker2";

export const AntiMatterCondenserAchievements: AchievementType[] = [
  {
    id: 341,
    name: "Antibatter",
    description: "Have 1 antimatter condenser",
    condition: 1,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 342,
    name: "Quirky quarks",
    description: "Have 50 antimatter condensers",
    condition: 50,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 343,
    name: "It does matter!",
    description: "Have 100 antimatter condensers",
    condition: 100,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 344,
    name: "Molecular maestro",
    description: "Have 150 antimatter condensers",
    condition: 150,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 345,
    name: "Walk the planck",
    description: "Have 200 antimatter condensers",
    condition: 200,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 346,
    name: "Microcosm",
    description: "Have 250 antimatter condensers",
    condition: 250,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 347,
    name: "Scientists baffled everywhere",
    description: "Have 300 antimatter condensers",
    condition: 300,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 348,
    name: "Exotic matter",
    description: "Have 350 antimatter condensers",
    condition: 350,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 349,
    name: "Downsizing",
    description: "Have 400 antimatter condensers",
    condition: 400,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 350,
    name: "A matter of perspective",
    description: "Have 450 antimatter condensers",
    condition: 450,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 351,
    name: "What a concept",
    description: "Have 500 antimatter condensers",
    condition: 500,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 352,
    name: "Particular tastes",
    description: "Have 550 antimatter condensers",
    condition: 550,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 353,
    name: "Nuclear throne",
    description: "Have 600 antimatter condensers",
    condition: 600,
    achievementType: "Having",

    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 354,
    name: "What;s the dark matter with you?",
    description: "Have 650 antimatter condensers",
    condition: 650,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 355,
    name: "Not 20 Years away forever",
    description: "Have 700 antimatter condensers",
    condition: 700,
    achievementType: "Having",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 356,
    name: "Supermassive",
    description: "Make 1 septillion cookies just from antimatter condensers.",
    condition: 1e24,
    achievementType: "Baking",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 357,
    name: "Infinitesimal",
    description: "Make 10 nonillion cookies just from antimatter condensers.",
    condition: 1e31,
    achievementType: "Baking",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 358,
    name: "Power of ten",
    description:
      "	Make 100 undecillion cookies just from antimatter condensers.",
    condition: 1e38,
    achievementType: "Baking",
    type: "antimatterCondenser",
    acquired: false,
  },
  {
    id: 359,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "antimatterCondenser",
    acquired: false,
  },
];
