import { AchievementType } from "../Cliker";

export const BankAchievements: AchievementType[] = [
  {
    id: 209,
    name: "Pretty penny",
    description: "Have 1 bank",
    condition: 1,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 210,
    name: "Fil the bill",
    description: "Have 50 banks",
    condition: 50,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 211,
    name: "A loan in the dark",
    description: "Have 100 banks",
    condition: 100,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 212,
    name: "Need for greed",
    description: "Have 150 banks",
    condition: 150,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 213,
    name: "it's the economy, stupid",
    description: "Have 200 banks",
    condition: 200,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 214,
    name: "Acquire currency",
    description: "Have 250 banks",
    condition: 250,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 215,
    name: "The nerve of war",
    description: "Have 300 banks",
    condition: 300,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 216,
    name: "And i need it now!",
    description: "Have 350 banks",
    condition: 350,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 217,
    name: "Treacle tart economics",
    description: "Have 400 banks",
    condition: 400,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 218,
    name: "Save your breath because that's all you've got left",
    description: "Have 450 banks",
    condition: 450,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },

  {
    id: 219,
    name: "Get the show on, get paid",
    description: "Have 500 banks",
    condition: 500,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 220,
    name: "Checks out",
    description: "Have 550 banks",
    condition: 550,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 221,
    name: "That's rich",
    description: "Have 600 banks",
    condition: 600,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 222,
    name: "Financial prodigy",
    description: "Have 650 banks",
    condition: 650,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 223,
    name: "Getting that bag",
    description: "Have 700 banks",
    condition: 700,
    achievementType: "Having",
    type: "bank",
    acquired: false,
  },
  {
    id: 224,
    name: "Vested interest",
    description: "Make 100 quadrillion cookies just from banks.",
    condition: 1e17,
    achievementType: "Baking",
    type: "bank",
    acquired: false,
  },
  {
    id: 225,
    name: "Paid in full",
    description: "Make 100 septillion cookies just from banks.",
    condition: 1e26,
    achievementType: "Baking",
    type: "bank",
    acquired: false,
  },
  {
    id: 226,
    name: "Reverse funnel system",
    description: "Make 10 nonillion cookies just from banks.",
    condition: 1e31,
    achievementType: "Baking",
    type: "bank",
    acquired: false,
  },
  {
    id: 227,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "factory",
    acquired: false,
  },
];
