import { AchievementType } from "../Cliker2";

export const ChangeMakerAchievement: AchievementType[] = [
  {
    id: 379,
    name: "Lucked out",
    description: "Have 1 chancemaker",
    condition: 1,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 380,
    name: "What are the odds",
    description: "Have 50 chancemakers",
    condition: 50,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 381,
    name: "Grandma needs a new pair of shoes",
    description: "Have 100 chancemakers",
    condition: 100,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 382,
    name: "Million to one shot",

    description: "Have 150 chancemakers",
    condition: 150,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 383,
    name: "As luck would have it",
    description: "Have 200 chancemakers",
    condition: 200,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 384,
    name: "Ever in your favor",
    description: "Have 250 chancemakers",
    condition: 250,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 385,
    name: "Be a lady",
    description: "Have 300 chancemakers",
    condition: 300,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 386,
    name: "Dicey business",
    description: "Have 350 chancemakers",
    condition: 350,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 387,
    name: "Maybe a chance in hell, actually",
    description: "Have 400 chancemakers",
    condition: 400,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 388,
    name: "Jackpot",
    description: "Have 450 chancemakers",
    condition: 450,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 389,
    name: "You'll never know if you don't go",
    description: "Have 500 chancemakers",
    condition: 500,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 390,
    name: "Tempting fate",
    description: "Have 550 chancemakers",
    condition: 550,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 391,
    name: "Flip a cookie. Chips, i win. Crust, you lose.",
    description: "Have 600 chancemakers",
    condition: 600,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 392,
    name: "Never tell me the odds",
    description: "Have 650 chancemakers",
    condition: 650,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 393,
    name: "Riding the Mersenne twister",
    description: "Have 700 chancemakers",
    condition: 700,
    achievementType: "Having",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 394,
    name: "Fingers crossed",
    description: "Make 100 septillion cookies just from chancemakers.",
    condition: 1e26,
    achievementType: "Baking",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 395,
    name: "Just a statistic",
    description: "Make 1 decillion cookies just from chancemakers.",
    condition: 1e33,
    achievementType: "Baking",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 396,
    name: "Murphy's wild guess",
    description: "Make 10 duodecillion cookies just from chancemakers.",
    condition: 1e42,
    achievementType: "Baking",
    type: "chancemaker",
    acquired: false,
  },
  {
    id: 397,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "chancemaker",
    acquired: false,
  },
];
