import { AchievementType } from "../Cliker";

export const JavascriptConsoleAchievement: AchievementType[] = [
  {
    id: 454,
    name: "It's big brain time",
    description: "Have 1 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 1,
    type: "cortexBaker",
  },
  {
    id: 455,
    name: "Just my imagination",
    description: "Have 50 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 50,
    type: "cortexBaker",
  },
  {
    id: 456,
    name: "Now there's an idea",
    description: "Have 100 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 100,
    type: "cortexBaker",
  },
  {
    id: 457,
    name: "The organ that named itself",
    description: "Have 150 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 150,
    type: "cortexBaker",
  },
  {
    id: 458,
    name: "Gyrification",
    description: "Have 200 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 200,
    type: "cortexBaker",
  },
  {
    id: 459,
    name: "A trademarked portmanteau of 'imagination' and 'engineering'",
    description: "Have 250 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 250,
    type: "cortexBaker",
  },
  {
    id: 460,
    name: "Mindfulness",
    description: "Have 300 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 300,
    type: "cortexBaker",
  },
  {
    id: 461,
    name: "The 10% myth",
    description: "Have 350 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 350,
    type: "cortexBaker",
  },
  {
    id: 462,
    name: "Don't think about it too hard",
    description: "Have 400 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 400,
    type: "cortexBaker",
  },
  {
    id: 463,
    name: "Though fool seldom differ",
    description: "Have 450 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 450,
    type: "cortexBaker",
  },
  {
    id: 464,
    name: "Looking kind of dumb",
    description: "Have 500 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 500,
    type: "cortexBaker",
  },
  {
    id: 465,
    name: "A beautiful mind",
    description: "Have 550 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 550,
    type: "cortexBaker",
  },
  {
    id: 466,
    name: "Cardinal synapses",
    description: "Have 600 cortex bakers",
    achievementType: "Having",
    acquired: true,
    condition: 600,
    type: "cortexBaker",
  },
  {
    id: 467,
    name: "By will alone i set my mind in motion",
    description: "Have 650 cortex bakers",
    achievementType: "Having",
    acquired: true,

    condition: 650,
    type: "cortexBaker",
  },
  {
    id: 468,
    name: "Where is my mind",
    description: "Have 700 cortex bakers",
    achievementType: "Having",

    acquired: true,
    condition: 700,
    type: "cortexBaker",
  },
  {
    id: 469,
    name: "Positive thinking",
    description: "Make 1 nonillion cookies just from cortex bakers.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e30,
    type: "cortexBaker",
  },
  {
    id: 470,
    name: "The thought that counts",
    description: "Make 10 undecillion cookies just from cortex bakers.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e37,
    type: "cortexBaker",
  },
  {
    id: 471,
    name: "Unthinkable",
    description: "Make 100 tredecillion cookies just from cortex bakers.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e44,
    type: "cortexBaker",
  },
  {
    id: 473,
    name: "TODO",
    description: "TODO",
    achievementType: "Baking",
    acquired: true,
    condition: 1e107,
    type: "cortexBaker",
  },
];
