import { AchievementType } from "../Cliker2";

export const Cursors: AchievementType[] = [
  {
    id: 113,
    name: "Click",
    description: "Have 1 cursor",
    condition: 1,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 114,
    name: "Double-click",
    description: "Have 2 cursors",
    condition: 2,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 115,
    name: "Mouse wheel",
    description: "Have 50 cursors",
    condition: 50,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 116,
    name: "Of Mice and Men",
    description: "Have 100 cursors",
    condition: 100,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 117,
    name: "The Digital",
    description: "Have 200 cursors",
    condition: 200,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 118,
    name: "Extreme polydactyly",
    description: "Have 300 cursors",
    condition: 300,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 119,
    name: "Dr. T",
    description: "Have 400 cursors",
    condition: 400,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 120,
    name: "Thumbs, phalanges, metacarpals",
    description: "Have 500 cursors",
    condition: 500,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 121,
    name: "With her finger and her thumb",
    description: "Have 600 cursors",
    condition: 600,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 122,
    name: "Gotta hand it to you",
    description: "Have 700 cursors",
    condition: 700,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 123,
    name: "The devil's workshop",
    description: "Have 800 cursors",
    condition: 800,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 124,
    name: "All hand on deck",
    description: "Have 900 cursors",
    condition: 900,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 125,
    name: "A round of applause",
    description: "Have 1,000 cursors",
    condition: 1000,
    achievementType: "Having",
    type: "cursor",
    acquired: false,
  },
  {
    id: 126,
    name: "Click delegator",
    description: "Make 10 Quintillion cookies just from cursors",
    condition: 10_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "cursor",
    acquired: false,
  },
  {
    id: 127,
    name: "Finger clickin' good",
    description: "Make 100 Sextillion cookies just from cursors",
    condition: 100_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "cursor",
    acquired: false,
  },
  {
    id: 128,
    name: "Click (starring Adam Sandler)",
    description: "Make 1 decillion cookies just from cursors.",
    condition: 1_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "cursor",
    acquired: false,
  },
  {
    id: 129,
    name: "Not Implemented",
    description: "TODO",
    condition: 1_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "cursor",
    acquired: false,
  },
];
