import { AchievementType } from "../Cliker2";

export const FactoryAchievements: AchievementType[] = [
  {
    id: 190,
    name: "Production chain",
    description: "Have 1 factory",
    condition: 1,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 191,
    name: "Industrial revolution",
    description: "Have 50 factories",
    condition: 50,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 192,
    name: "Globalization",
    description: "Have 100 factories",
    condition: 100,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 193,
    name: "Ultimate automation",
    description: "Have 150 factories",
    condition: 150,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 194,
    name: "Technocracy",
    description: "Have 200 factories",
    condition: 200,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 195,
    name: "Rise of the machines",
    description: "Have 250 factories",

    condition: 250,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 196,
    name: "Modern times",
    description: "Have 300 factories",
    condition: 300,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 197,
    name: "Ex Machina",
    description: "Have 350 factories",
    condition: 350,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 198,
    name: "In full gear",
    description: "Have 400 factories",
    condition: 400,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 199,
    name: "In-cog-neato",
    description: "Have 450 factories",
    condition: 450,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 200,
    name: "Break the mold",
    description: "Have 500 factories",
    condition: 500,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 201,
    name: "Self-manmade man",
    description: "Have 550 factories",
    condition: 550,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 202,
    name: "The wheels of progress",
    description: "Have 600 factories",
    condition: 600,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 203,
    name: "Replaced by robots",
    description: "Have 650 factories",
    condition: 650,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 204,
    name: "Bots build bots",
    description: "Have 700 factories",
    condition: 700,
    achievementType: "Having",
    type: "factory",
    acquired: false,
  },
  {
    id: 205,
    name: "The incredible machine",
    description: "Make 10 quadrillion cookies just from factories.",
    condition: 1e16,
    achievementType: "Baking",
    type: "factory",
    acquired: false,
  },
  {
    id: 206,
    name: "Yes I love technology",
    description: "Make 100 sextillion cookies just from factories.",
    condition: 1e23,
    achievementType: "Baking",
    type: "factory",
    acquired: false,
  },
  {
    id: 207,
    name: "Labor of love",
    description: "Make 1 nonillion cookies just from factories.",
    condition: 1e30,
    achievementType: "Baking",
    type: "factory",
    acquired: false,
  },
  {
    id: 208,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "factory",
    acquired: false,
  },
];
