import { AchievementType } from "../Cliker";

export const FarmAchievements: AchievementType[] = [
  {
    id: 152,
    name: "My first farm",
    description: "Have 1 farm",
    condition: 1,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 153,
    name: "Reap what you sow",
    description: "Have 50 farms",
    condition: 50,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 154,
    name: "Farm ill",
    description: "Have 100 farms",
    condition: 100,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 155,
    name: "Perfected agriculture",
    description: "Have 150 farms",
    condition: 150,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 156,
    name: "Homegrown",
    description: "Have 200 farms",
    condition: 200,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 157,
    name: "Gardener extraordinaire",
    description: "Have 250 farms",
    condition: 250,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 158,
    name: "Seedy business",
    description: "Have 300 farms",
    condition: 300,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 159,
    name: "You and the beanstalk",
    description: "Have 350 farms",
    condition: 350,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 160,
    name: "Harvest moon",
    description: "Have 400 farms",
    condition: 400,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 161,
    name: "Make like a tree",
    description: "Have 450 farms",
    condition: 450,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 162,
    name: "Sharpest tool in the shed",
    description: "Have 500 farms",
    condition: 500,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 163,
    name: "Overripe",
    description: "Have 550 farms",
    condition: 550,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 164,
    name: "in the green",
    description: "Have 600 farms",
    condition: 600,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 165,
    name: "it's grown on you",
    description: "Have 650 farms",
    condition: 650,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 166,
    name: "Au naturel",
    description: "Have 700 farms",
    condition: 700,
    achievementType: "Having",
    type: "farm",
    acquired: false,
  },
  {
    id: 167,
    name: "I hate manure",
    description: "Make 100 trillion cookies just from farms",
    condition: 100_000_000_000_000,
    achievementType: "Baking",
    type: "farm",
    acquired: false,
  },
  {
    id: 168,
    name: "Rake in the dough",
    description: "Make 1 sextillion cookies just from farms",
    condition: 1_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "farm",
    acquired: false,
  },
  {
    id: 169,
    name: "Overgrowth",
    description: "Make 10 Octillion cookies just from farms",
    condition: 10_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "farm",
    acquired: false,
  },
  {
    id: 170,
    name: "Not Implemented",
    description: "TODO",
    condition: 1_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "farm",
    acquired: false,
  },
];
