import { AchievementType } from "../Cliker";

export const FractalEngineAchievements: AchievementType[] = [
  {
    id: 398,
    name: "Self-contained",
    description: "Have 1 Fractal Engine",
    achievementType: "Having",
    acquired: false,
    condition: 1,
    type: "fractalEngine",
  },
  {
    id: 399,
    name: "Threw you for a loop",
    description: "Have 50 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 50,
    type: "fractalEngine",
  },
  {
    id: 400,
    name: "The sum of its parts",
    description: "Have 100 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 100,
    type: "fractalEngine",
  },
  {
    id: 401,
    name: "Bears repeating",
    description: "Have 150 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 150,
    type: "fractalEngine",
  },
  {
    id: 402,
    name: "More of the same",
    description: "Have 200 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 200,
    type: "fractalEngine",
  },
  {
    id: 403,
    name: "Last recurse",
    description: "Have 250 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 250,
    type: "fractalEngine",
  },
  {
    id: 404,
    name: "Out of one, many",
    description: "Have 300 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 300,
    type: "fractalEngine",
  },
  {
    id: 405,
    name: "An example of recursion",
    description: "Have 350 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 350,
    type: "fractalEngine",
  },
  {
    id: 406,
    name: "For more information on this achievement, please refer to its title",
    description: "Have 400 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 400,
    type: "fractalEngine",
  },
  {
    id: 407,
    name: "I'm so meta, even this achievement",
    description: "Have 450 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 450,
    type: "fractalEngine",
  },
  {
    id: 408,
    name: "Never got bored",
    description: "Have 500 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 500,
    type: "fractalEngine",
  },
  {
    id: 409,
    name: "Tautological",
    description: "Have 550 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 550,
    type: "fractalEngine",
  },
  {
    id: 410,
    name: "In and of itself",
    description: "Have 600 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 600,
    type: "fractalEngine",
  },
  {
    id: 411,
    name: "Blowing an Apollonian gasket",
    description: "Have 650 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 650,
    type: "fractalEngine",
  },
  {
    id: 412,
    name: "Divide and conquer",
    description: "Have 700 Fractal Engines",
    achievementType: "Having",
    acquired: false,
    condition: 700,
    type: "fractalEngine",
  },
  {
    id: 413,
    name: "The needs of the many",
    description: "Make 1 octillion cookies just from fractal engines.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e27,
    type: "fractalEngine",
  },
  {
    id: 414,
    name: "Eating its own",
    description: "Make 10 decillion cookies just from fractal engines.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e34,
    type: "fractalEngine",
  },
  {
    id: 415,
    name: "We must go deeper",
    description: "Make 100 duodecillion cookies just from fractal engines.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e41,
    type: "fractalEngine",
  },
  {
    id: 416,
    name: "TODO",
    description: "TODO",
    achievementType: "Baking",
    acquired: false,
    condition: 1e104,
    type: "fractalEngine",
  },
];
