import { AchievementType } from "../Cliker2";

export const GrandmaAchievements: AchievementType[] = [
  {
    id: 130,
    name: "Grandma's cookies",
    description: "Have 1 grandma",
    condition: 1,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 131,
    name: "Sloppy kisses",
    description: "Have 50 grandmas",
    condition: 50,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 132,
    name: "Retirement home",
    description: "Have 100 grandmas",
    condition: 100,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 133,
    name: "Corporate synergy",
    description: "Have 125 grandmas",
    condition: 125,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 134,
    name: "Friend of the ancients",
    description: "Have 150 grandmas",
    condition: 150,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 135,
    name: "Come to grandma",
    description: "Have 150 grandmas",
    condition: 150,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 136,
    name: "Ruler of the ancients",
    description: "Have 200 grandmas",
    condition: 200,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 137,
    name: "The old never bothered me anyway",
    description: "Have 250 grandmas",
    condition: 250,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 138,
    name: "The agemaster",
    description: "Have 300 grandmas",
    condition: 300,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 139,
    name: "To oldly go",
    description: "Have 350 grandmas",
    condition: 350,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 140,
    name: "Gushing grannies",
    description: "Have 375 grandmas",
    condition: 375,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 141,
    name: "Aged well",
    description: "Have 400 grandmas",
    condition: 400,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 142,
    name: "101st birthday",
    description: "Have 450 grandmas",
    condition: 450,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 143,
    name: "But wait 'til you get older",
    description: "Have 500 grandmas",
    condition: 500,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 144,
    name: "Defense of the ancients",
    description: "Have 550 grandmas",
    condition: 550,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 145,
    name: "Okay boomer",
    description: "Have 600 grandmas",
    condition: 600,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 146,
    name: "They moistly come at night",
    description: "Have 650 grandmas",
    condition: 650,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 147,
    name: "And now you're even older",
    description: "Have 700 grandmas",
    condition: 700,
    achievementType: "Having",
    type: "grandma",
    acquired: false,
  },
  {
    id: 148,
    name: "Gushing grannies",
    description: "Make 10 quintillion cookies just from grandmas",
    condition: 10_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "grandma",
    acquired: false,
  },
  {
    id: 149,
    name: "Panic at the bingo",
    description: "Make 100 septillion cookies just from grandmas",
    condition: 100_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "grandma",
    acquired: false,
  },
  {
    id: 150,
    name: "Frantiquites",
    description: "Make 1 decillion cookies just from grandmas",
    condition: 1_000_000_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "grandma",
    acquired: false,
  },
  {
    id: 151,
    name: "Not Implemented",
    description: "TODO",
    condition: 1_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
    achievementType: "Baking",
    type: "grandma",
    acquired: false,
  },
];
