import { AchievementType } from "../Cliker2";

export const IdleVerseAchievements: AchievementType[] = [
  {
    id: 435,
    name: "They'll never know what hit them",
    description: "Have 1 Idle Verse",
    achievementType: "Having",
    acquired: true,
    condition: 1,
    type: "idleverse",
  },
  {
    id: 436,
    name: "Well-versed",
    description: "Have 50 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 50,
    type: "idleverse",
  },
  {
    id: 437,
    name: "Ripe for the picking",
    description: "Have 100 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 100,
    type: "idleverse",
  },
  {
    id: 438,
    name: "Unreal",
    description: "Have 150 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 150,
    type: "idleverse",
  },
  {
    id: 439,
    name: "Once you've seen one",
    description: "Have 200 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 200,
    type: "idleverse",
  },
  {
    id: 440,
    name: "Spoils and plunder",
    description: "Have 250 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 250,
    type: "idleverse",
  },
  {
    id: 441,
    name: "Nobody exists on purpose, nobody belongs anywhere",
    description: "Have 300 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 300,
    type: "idleverse",
  },
  {
    id: 442,
    name: "Hyperspace expressway",
    description: "Have 350 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 350,
    type: "idleverse",
  },
  {
    id: 443,
    name: "Versatile",
    description: "Have 400 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 400,
    type: "idleverse",
  },
  {
    id: 444,
    name: "You are inevitable",
    description: "Have 450 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 450,
    type: "idleverse",
  },
  {
    id: 445,
    name: "Away from this place",
    description: "Have 500 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 500,
    type: "idleverse",
  },
  {
    id: 446,
    name: "Everywhere at once",
    description: "Have 550 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 550,
    type: "idleverse",
  },
  {
    id: 447,
    name: "Reject reality, substitute your own",
    description: "Have 600 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 600,
    type: "idleverse",
  },
  {
    id: 448,
    name: "Lost your cosmic marbles",
    description: "Have 650 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 650,
    type: "idleverse",
  },
  {
    id: 449,
    name: "Greener on the other side",
    description: "Have 700 Idle Verses",
    achievementType: "Having",
    acquired: true,
    condition: 700,
    type: "idleverse",
  },
  {
    id: 450,
    name: "Fringe",
    description: "Make 100 octillion cookies just from idleverses.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e29,
    type: "idleverse",
  },
  {
    id: 451,
    name: "Coherence",
    description: "Make 1 undecillion cookies just from idleverses.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e36,
    type: "idleverse",
  },
  {
    id: 452,
    name: "Earth-616",
    description: "Make 10 tredecillion cookies just from idleverses.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e43,
    type: "idleverse",
  },
  {
    id: 453,
    name: "TODO",
    description: "TODO",
    achievementType: "Baking",
    acquired: true,
    condition: 1e106,
    type: "idleverse",
  },
];
