import { AchievementType } from "../Cliker";

export const JavascriptConsoleAchievement: AchievementType[] = [
  {
    id: 416,
    name: "F12",
    description: "Have 1 Javascript Console",
    achievementType: "Having",
    acquired: false,
    condition: 1,
    type: "javascriptConsole",
  },
  {
    id: 417,
    name: "Variable success",
    description: "Have 50 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 50,
    type: "javascriptConsole",
  },
  {
    id: 418,
    name: "No comments",
    description: "Have 100 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 100,
    type: "javascriptConsole",
  },
  {
    id: 419,
    name: "Up to code",
    description: "Have 150 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 150,
    type: "javascriptConsole",
  },
  {
    id: 420,
    name: "Works on my machine",
    description: "Have 200 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 200,
    type: "javascriptConsole",
  },
  {
    id: 421,
    name: "Technical debt",
    description: "Have 250 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 250,
    type: "javascriptConsole",
  },
  {
    id: 422,
    name: "Mind your language",
    description: "Have 300 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 300,
    type: "javascriptConsole",
  },
  {
    id: 423,
    name: "Inconsolable",
    description: "Have 350 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 350,
    type: "javascriptConsole",
  },
  {
    id: 424,
    name: "Closure",
    description: "Have 400 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 400,
    type: "javascriptConsole",
  },
  {
    id: 425,
    name: "Dude what if we're all living in a simulation like what if we're all just code on a computer somewhere",
    description: "Have 450 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 450,
    type: "javascriptConsole",
  },
  {
    id: 426,
    name: "Taking the back streets",
    description: "Have 500 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 500,
    type: "javascriptConsole",
  },
  {
    id: 427,
    name: "Curly braces",
    description: "Have 550 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 550,
    type: "javascriptConsole",
  },
  {
    id: 428,
    name: "Duck typing",
    description: "Have 600 Javascript Consoles",
    achievementType: "Having",
    acquired: false,
    condition: 600,
    type: "javascriptConsole",
  },
  {
    id: 429,
    name: "Glucosmium javascript console	Get with the program",
    description: "Have 650 Javascript Consoles",
    achievementType: "Having",
    acquired: false,

    condition: 650,
    type: "javascriptConsole",
  },
  {
    id: 430,
    name: "Pebcakes",
    description: "Have 700 Javascript Consoles",
    achievementType: "Having",

    acquired: false,
    condition: 700,
    type: "javascriptConsole",
  },
  {
    id: 431,
    name: "Inherited prototype",
    description: "Make 10 octillion cookies just from javascript consoles.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e28,
    type: "javascriptConsole",
  },
  {
    id: 432,
    name: "A model of document object",
    description: "Make 100 decillion cookies just from javascript consoles.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e35,
    type: "javascriptConsole",
  },
  {
    id: 433,
    name: "First-class citizen",
    description: "Make 1 tredecillion cookies just from javascript consoles.",
    achievementType: "Baking",
    acquired: false,
    condition: 1e42,
    type: "javascriptConsole",
  },
  {
    id: 434,
    name: "TODO",
    description: "TODO",
    achievementType: "Baking",
    acquired: false,
    condition: 1e105,
    type: "javascriptConsole",
  },
];
