import { AchievementType } from "../Cliker2";

export const Mines: AchievementType[] = [
  {
    id: 171,
    name: "You know the drill",
    description: "Have 1 mine",
    condition: 1,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 172,
    name: "Excavation site",
    description: "Have 50 mines",
    condition: 50,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 173,
    name: "Hollow the earth",
    description: "Have 100 mines",
    condition: 100,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 174,
    name: "Can you dig it?",
    description: "Have 150 mines",
    condition: 150,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 175,
    name: "Center of the earth",
    description: "Have 200 mines",
    condition: 200,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 176,
    name: "Tecktonic ambassador",
    description: "Have 250 mines",
    condition: 250,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 177,
    name: "Freak fracking",
    description: "Have 300 mines",
    condition: 300,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 178,
    name: "Romancing the stone",
    description: "Have 350 mines",
    condition: 350,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 179,
    name: "Mine?",
    description: "Have 400 mines",
    condition: 400,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 180,
    name: "Cave story",
    description: "Have 450 mines",
    condition: 450,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 181,
    name: "Hey now, you're a rock",
    description: "Have 500 mines",
    condition: 500,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 182,
    name: "Rock on",
    description: "Have 550 mines",
    condition: 550,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 183,
    name: "Mountain out of a molehill, but like in a good way",
    description: "Have 600 mines",
    condition: 600,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 184,
    name: "Don't let the walls cave in on you",
    description: "Have 650 mines",
    condition: 650,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 185,
    name: "Dirt-rich",
    description: "Have 700 mines",
    condition: 700,
    achievementType: "Having",
    type: "mine",
    acquired: false,
  },
  {
    id: 186,
    name: "Never dig down",
    description: "Make 1 quadrillion of cookies from mines",
    condition: 1e15,
    achievementType: "Baking",
    type: "mine",
    acquired: false,
  },
  {
    id: 187,
    name: "Quarry on",
    description: "Make 10 sextillion of cookies from mines",
    condition: 1e22,
    achievementType: "Baking",
    type: "mine",
    acquired: false,
  },
  {
    id: 188,
    name: "Sedimentalism",
    description: "Make 100 octillion of cookies from mines",
    condition: 1e29,
    achievementType: "Baking",
    type: "mine",
    acquired: false,
  },
  {
    id: 189,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "mine",
    acquired: false,
  },
];
