import { AchievementType } from "../Cliker";

export const PortalAchievements: AchievementType[] = [
  {
    id: 304,
    name: "A whole new world",
    description: "Have 1 portal",
    condition: 1,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 305,
    name: "Now you're thinking",
    description: "Have 50 portals",
    condition: 50,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 306,
    name: "Dimensional shift",
    description: "Have 100 portals",
    condition: 100,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 307,
    name: "Brain-split",
    description: "Have 150 portals",
    condition: 150,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 308,
    name: "Realm of the Mad God",
    description: "Have 200 portals",
    condition: 200,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 309,
    name: "A place lost in time",
    description: "Have 250 portals",
    condition: 250,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 310,
    name: "Forbidden zone",
    description: "Have 300 portals",
    condition: 300,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 311,
    name: "H̸̷̢̛̭̣̲̗̦̦͡",
    description: "Have 350 portals",
    condition: 350,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 312,
    name: "	What happens in the vortex stays in the vortex",
    description: "Have 400 portals",
    condition: 400,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 313,
    name: "Objects in the mirror dimension are closer than they appear",
    description: "Have 450 portals",
    condition: 450,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 314,
    name: "Your brain gets smart but your head gets dumb",
    description: "Have 500 portals",
    condition: 500,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 315,
    name: "Don't let me leave, Murph",
    description: "Have 550 portals",
    condition: 550,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 316,
    name: "Reduced to gibbering heaps",
    description: "Have 600 portals",
    condition: 600,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 317,
    name: "Swiss cheese universe",
    description: "Have 650 portals",
    condition: 650,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 318,
    name: "Not even remotely close to Kansas anymore",
    description: "Have 700 portals",
    condition: 700,
    achievementType: "Having",
    type: "portal",
    acquired: false,
  },
  {
    id: 319,
    name: "With strange eons",
    description: "Make 10 sextillion cookies just from portals.",
    condition: 1e22,
    achievementType: "Baking",
    type: "portal",
    acquired: false,
  },
  {
    id: 320,
    name: "Ever more hideous",
    description: "Make 100 octillion cookies just from portals.",
    condition: 1e29,
    achievementType: "Baking",
    type: "portal",
    acquired: false,
  },
  {
    id: 321,
    name: "Which eternal lie",
    description: "Make 1 undecillion cookies just from portals.",
    condition: 1e36,
    achievementType: "Baking",
    type: "portal",
    acquired: false,
  },
  {
    id: 322,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "portal",
    acquired: false,
  },
];
