import { AchievementType } from "../Cliker2";

export const PrismAchievements: AchievementType[] = [
  {
    id: 360,
    name: "Lone photon",
    description: "Have 1 prism",
    condition: 1,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 361,
    name: "Dazzling glimmer",
    description: "Have 50 prisms",
    condition: 50,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 362,
    name: "Blinding flash",
    description: "Have 100 prisms",
    condition: 100,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 363,
    name: "Unending glow",
    description: "Have 150 prisms",
    condition: 150,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 364,
    name: "Rise and shine",
    description: "Have 200 prisms",
    condition: 200,

    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 365,
    name: "Bright future",
    description: "Have 250 prisms",
    condition: 250,
    achievementType: "Having",

    type: "prism",
    acquired: false,
  },
  {
    id: 366,
    name: "Harmony of the spheres",
    description: "Have 300 prisms",
    condition: 300,
    achievementType: "Having",

    type: "prism",
    acquired: false,
  },
  {
    id: 367,
    name: "At the end of the tunnel",
    description: "Have 350 prisms",
    condition: 350,
    achievementType: "Having",

    type: "prism",
    acquired: false,
  },
  {
    id: 368,
    name: "My eyes",
    description: "Have 400 prisms",
    condition: 400,
    achievementType: "Having",

    type: "prism",
    acquired: false,
  },
  {
    id: 369,
    name: "Optical illusion",
    description: "Have 450 prisms",
    condition: 450,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 370,
    name: "You'll never shine if you don't glow",
    description: "Have 500 prisms",
    condition: 500,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 371,
    name: " A light snack",
    description: "Have 550 prisms",
    condition: 550,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 372,
    name: "Making light of the situation",
    description: "Have 600 prisms",
    condition: 600,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 373,
    name: "Enlightenment",
    description: "Have 650 prisms",

    condition: 650,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 374,
    name: "Bright side of the moon",
    description: "Have 700 prisms",
    condition: 700,
    achievementType: "Having",
    type: "prism",
    acquired: false,
  },
  {
    id: 375,
    name: "Praise the sun",
    description: "Make 10 septillion cookies just from prisms.",
    condition: 1e25,
    achievementType: "Baking",
    type: "prism",
    acquired: false,
  },
  {
    id: 376,
    name: "A still more glorious dawn awaits",
    description: "Make 100 nonillion cookies just from prisms.",
    condition: 1e32,
    achievementType: "Baking",
    type: "prism",
    acquired: false,
  },
  {
    id: 377,
    name: "Now the dark days are gone",
    description: "Make 1 duodecillion cookies just from prisms.",
    condition: 1e39,
    achievementType: "Baking",
    type: "prism",
    acquired: false,
  },
  {
    id: 378,
    name: "Todo",
    description: "Todo",
    condition: 1e96,
    achievementType: "Baking",
    type: "prism",
    acquired: false,
  },
];
