import { AchievementType } from "../Cliker";

export const ShipmentAchievements: AchievementType[] = [
  {
    id: 266,
    name: "Expedition",
    description: "Have 1 shipment",
    condition: 1,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 267,
    name: "Galactic highway",
    description: "Have 50 shipments",
    condition: 50,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 268,
    name: "Far far away",
    description: "Have 100 shipments",
    condition: 100,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 269,
    name: "Type II civilization",
    description: "Have 150 shipments",
    condition: 150,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 270,
    name: "We come in peace",
    description: "Have 200 shipments",
    condition: 200,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 271,
    name: "Parsec-masher",
    description: "Have 250 shipments",
    condition: 250,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 272,
    name: "It's not delivery",
    description: "Have 300 shipments",
    condition: 300,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 273,
    name: "Make it so",
    description: "Have 350 shipments",
    condition: 350,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 274,
    name: "That's just peanuts to space",
    description: "Have 400 shipments",
    condition: 400,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 275,
    name: "Space space space space space",
    description: "Have 450 shipments",
    condition: 450,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 276,
    name: "Only shooting stars",
    description: "Have 500 shipments",
    condition: 500,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 277,
    name: "The incredible journey",
    description: "Have 550 shipments",
    condition: 550,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 278,
    name: "Is there life on Mars?",
    description: "Have 600 shipments",
    condition: 600,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 279,
    name: "False vacuum",
    description: "Have 650 shipments",
    condition: 650,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 280,
    name: "Signed, sealed ,delivered",
    description: "Have 700 shipments",
    condition: 700,
    achievementType: "Having",
    type: "shipment",
    acquired: false,
  },
  {
    id: 281,
    name: "And beyond",
    description: "Make 100 quintillion cookies just from shipments.",
    condition: 1e20,
    achievementType: "Baking",
    type: "shipment",
    acquired: false,
  },
  {
    id: 282,
    name: "The most precious cargo",
    description: "Make 1 octillion cookies just from shipments.",
    condition: 1e27,
    achievementType: "Baking",
    type: "shipment",
    acquired: false,
  },
  {
    id: 283,
    name: "Neither snow nor rain nor heat nor gloom of night",
    description: "Make 10 decillion cookies just from shipments.",
    condition: 1e34,
    achievementType: "Baking",
    type: "shipment",
    acquired: false,
  },
  {
    id: 284,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "shipment",
    acquired: false,
  },
];
