import { AchievementType } from "../Cliker";

export const TempleAchievements: AchievementType[] = [
  {
    id: 228,
    name: "Your time to shrine",
    description: "Have 1 temple",
    condition: 1,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 229,
    name: "Shady sect",
    description: "Have 50 temples",
    condition: 50,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 230,
    name: "New-age cult",
    description: "Have 100 temples",
    condition: 100,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 231,
    name: "Organized religion",
    description: "Have 150 temples",
    condition: 150,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 232,
    name: "Fanaticism",
    description: "Have 200 temples",
    condition: 200,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 233,
    name: "Zealotry",

    description: "Have 250 temples",
    condition: 250,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 234,
    name: "Wololo",
    description: "Have 300 temples",

    condition: 300,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 235,
    name: "Pray on the weak",
    description: "Have 350 temples",
    condition: 350,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 236,
    name: "Holy cookies, grandma!",
    description: "Have 400 temples",
    condition: 400,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 237,
    name: "Vengeful and almighty",
    description: "Have 450 temples",
    condition: 450,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 238,
    name: "My world's on fire, how about yours?",
    description: "Have 500 temples",
    condition: 500,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 239,
    name: "Living on a prayer",
    description: "Have 550 temples",
    condition: 550,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 240,
    name: "Preaching to the choir",
    description: "Have 600 temples",
    condition: 600,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 241,
    name: "And i will pray to a big god",
    description: "Have 650 temples",
    condition: 650,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 242,
    name: "The Leader is good , the leader is great",
    description: "Have 700 temples",
    condition: 700,
    achievementType: "Having",
    type: "temple",
    acquired: false,
  },
  {
    id: 243,
    name: "New world order",
    description: "Make 1 quintillion cookies just from temples.",
    condition: 1e18,
    achievementType: "Baking",
    type: "temple",
    acquired: false,
  },
  {
    id: 244,
    name: "Church of cookiology",
    description: "Make 10 septillion cookies just from temples.",
    condition: 1e25,
    achievementType: "Baking",
    type: "temple",
    acquired: false,
  },
  {
    id: 245,
    name: "thus spoke cookierathustra",
    description: "Make 100 nonillion cookies just from temples.",
    condition: 1e32,
    achievementType: "Baking",
    type: "temple",
    acquired: false,
  },
  {
    id: 246,
    name: "Todo",
    description: "Todo",
    condition: 1e96,
    achievementType: "Baking",
    type: "temple",
    acquired: false,
  },
];
