import { AchievementType } from "../Cliker2";

export const TimeMachineAchievement: AchievementType[] = [
  {
    id: 323,
    name: "Time warp",
    description: "Have 1 time machine",
    condition: 1,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 324,
    name: "Alternate timeline",
    description: "Have 50 time machines",
    condition: 50,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 325,
    name: "Rewriting history",
    description: "Have 100 time machines",
    condition: 100,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 326,
    name: "Time duke",
    description: "Have 150 time machines",
    condition: 150,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 327,
    name: "Forever isn't that long",
    description: "Have 200 time machines",
    condition: 200,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 328,
    name: "Heat death",
    description: "Have 250 time machines",
    condition: 250,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 329,
    name: "Cookie clicker forever and forever a hundred years cookie clicker",
    description: "Have 300 time machines",
    condition: 300,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 330,
    name: "Way back then",
    description: "Have 350 time machines",
    condition: 350,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 331,
    name: "Invited to yesterday's party",
    description: "Have 400 time machines",
    condition: 400,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 332,
    name: "Groundhog day",
    description: "Have 450 time machines",
    condition: 450,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 333,
    name: "The years start coming",
    description: "Have 500 time machines",
    condition: 500,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 334,
    name: "Caveman to cosmos",
    description: "Have 550 time machines",
    condition: 550,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 335,
    name: "Back already?",
    description: "Have 600 time machines",
    condition: 600,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 336,
    name: "But the future refused to change",
    description: "Have 650 time machines",
    condition: 650,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 337,
    name: "I only meant to stay awhile",
    description: "Have 700 time machines",
    condition: 700,
    achievementType: "Having",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 338,
    name: "Spacetime jigamaroo",
    description: "Make 100 sextillion cookies just from time machines.",
    condition: 1e23,
    achievementType: "Baking",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 339,
    name: "Be kind, rewind",
    description: "Make 1 nonillion cookies just from time machines.",
    condition: 1e30,
    achievementType: "Baking",
    type: "timeMachine",
    acquired: false,
  },
  {
    id: 340,
    name: "Déjà vu",
    description: "	Make 10 undecillion cookies just from time machines.",
    condition: 1e37,
    achievementType: "Baking",
    type: "timeMachine",
    acquired: false,
  },
];
