import { AchievementType } from "../Cliker";

export const TotalBuildingAndUpgradesAchievements: AchievementType[] = [
  {
    id: 1000,
    name: "Build 50 buildings",
    description: "Build 50 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 50,
    type: "Owned Buildings",
  },
  {
    id: 1001,
    name: "Build 100 buildings",
    description: "Build 100 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 100,
    type: "Owned Buildings",
  },
  {
    id: 1002,
    name: "Build 150 buildings",
    description: "Build 150 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 150,
    type: "Owned Buildings",
  },
  {
    id: 1003,
    name: "Build 200 buildings",
    description: "Build 200 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 200,
    type: "Owned Buildings",
  },
  {
    id: 1004,
    name: "Build 250 buildings",
    description: "Build 250 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 250,
    type: "Owned Buildings",
  },
  {
    id: 1005,
    name: "Build 300 buildings",
    description: "Build 300 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 300,
    type: "Owned Buildings",
  },
  {
    id: 1006,
    name: "Build 350 buildings",
    description: "Build 350 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 350,
    type: "Owned Buildings",
  },
  {
    id: 1007,
    name: "Build 400 buildings",
    description: "Build 400 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 400,
    type: "Owned Buildings",
  },
  {
    id: 1008,
    name: "Build 450 buildings",
    description: "Build 450 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 450,
    type: "Owned Buildings",
  },
  {
    id: 1009,
    name: "Build 500 buildings",
    description: "Build 500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 500,
    type: "Owned Buildings",
  },
  {
    id: 1010,
    name: "Build 550 buildings",
    description: "Build 550 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 550,
    type: "Owned Buildings",
  },
  {
    id: 1011,
    name: "Build 600 buildings",
    description: "Build 600 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 600,
    type: "Owned Buildings",
  },
  {
    id: 1012,
    name: "Build 650 buildings",
    description: "Build 650 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 650,
    type: "Owned Buildings",
  },
  {
    id: 1013,
    name: "Build 700 buildings",
    description: "Build 700 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 700,
    type: "Owned Buildings",
  },
  {
    id: 1014,
    name: "Build 750 buildings",
    description: "Build 750 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 750,
    type: "Owned Buildings",
  },
  {
    id: 1015,
    name: "Build 800 buildings",
    description: "Build 800 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 800,
    type: "Owned Buildings",
  },
  {
    id: 1016,
    name: "Build 900 buildings",
    description: "Build 900 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 900,
    type: "Owned Buildings",
  },
  {
    id: 1017,
    name: "Build 1000 buildings",
    description: "Build 1000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1000,
    type: "Owned Buildings",
  },
  {
    id: 1018,
    name: "Build 1100 buildings",
    description: "Build 1100 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1100,
    type: "Owned Buildings",
  },
  {
    id: 1019,
    name: "Build 1200 buildings",
    description: "Build 1200 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1200,
    type: "Owned Buildings",
  },
  {
    id: 1020,
    name: "Build 1300 buildings",
    description: "Build 1300 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1300,
    type: "Owned Buildings",
  },
  {
    id: 1021,
    name: "Build 1400 buildings",
    description: "Build 1400 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1400,
    type: "Owned Buildings",
  },
  {
    id: 1022,
    name: "Build 1500 buildings",
    description: "Build 1500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1500,
    type: "Owned Buildings",
  },
  {
    id: 1023,
    name: "Build 1700 buildings",
    description: "Build 1700 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1700,
    type: "Owned Buildings",
  },
  {
    id: 1024,
    name: "Build 1900 buildings",
    description: "Build 1900 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 1900,
    type: "Owned Buildings",
  },
  {
    id: 1025,
    name: "Build 2100 buildings",
    description: "Build 2100 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 2100,
    type: "Owned Buildings",
  },
  {
    id: 1026,
    name: "Build 2300 buildings",
    description: "Build 2300 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 2300,
    type: "Owned Buildings",
  },
  {
    id: 1027,
    name: "Build 2500 buildings",
    description: "Build 2500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 2500,
    type: "Owned Buildings",
  },
  {
    id: 1028,
    name: "Build 2700 buildings",
    description: "Build 2700 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 2700,
    type: "Owned Buildings",
  },
  {
    id: 1029,
    name: "Build 2900 buildings",
    description: "Build 2900 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 2900,
    type: "Owned Buildings",
  },
  {
    id: 1030,
    name: "Build 3100 buildings",
    description: "Build 3100 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 3100,
    type: "Owned Buildings",
  },
  {
    id: 1031,
    name: "Build 3500 buildings",
    description: "Build 3500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 3500,
    type: "Owned Buildings",
  },
  {
    id: 1032,
    name: "Build 4000 buildings",
    description: "Build 4000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 4000,
    type: "Owned Buildings",
  },
  {
    id: 1033,
    name: "Build 4500 buildings",
    description: "Build 4500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 4500,
    type: "Owned Buildings",
  },
  {
    id: 1034,
    name: "Build 5000 buildings",
    description: "Build 5000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 5000,
    type: "Owned Buildings",
  },
  {
    id: 1035,
    name: "Build 5500 buildings",
    description: "Build 5500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 5500,
    type: "Owned Buildings",
  },
  {
    id: 1036,
    name: "Build 6000 buildings",
    description: "Build 6000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 6000,
    type: "Owned Buildings",
  },
  {
    id: 1037,
    name: "Build 6500 buildings",
    description: "Build 6500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 6500,
    type: "Owned Buildings",
  },
  {
    id: 1038,
    name: "Build 7000 buildings",
    description: "Build 7000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 7000,
    type: "Owned Buildings",
  },
  {
    id: 1039,
    name: "Build 7500 buildings",
    description: "Build 7500 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 7500,
    type: "Owned Buildings",
  },
  {
    id: 1040,
    name: "Build 8000 buildings",
    description: "Build 8000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 8000,
    type: "Owned Buildings",
  },
  {
    id: 1041,
    name: "Build 9000 buildings",
    description: "Build 9000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 9000,
    type: "Owned Buildings",
  },
  {
    id: 1042,
    name: "Build 10000 buildings",
    description: "Build 10000 buildings",
    achievementType: "Having",
    acquired: false,
    condition: 10000,
    type: "Owned Buildings",
  },
  {
    id: 1043,
    name: "My first upgrade",
    description: "Buy your first upgrade",
    achievementType: "Having",
    acquired: false,
    condition: 1,
    type: "Purchase Upgrades",
  },
  {
    id: 1044,
    name: "Look at all these upgrades",
    description: "Buy 10 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 10,
    type: "Purchase Upgrades",
  },
  {
    id: 1045,
    name: "I'm rich",
    description: "Buy 15 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 15,
    type: "Purchase Upgrades",
  },
  {
    id: 1046,
    name: "Enhancer",
    description: "Buy 20 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 20,
    type: "Purchase Upgrades",
  },
  {
    id: 1047,
    name: "I'm a god",
    description: "Buy 25 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 25,
    type: "Purchase Upgrades",
  },
  {
    id: 1048,
    name: "Upgrades are my life",
    description: "Buy 30 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 30,
    type: "Purchase Upgrades",
  },
  {
    id: 1049,
    name: "Not enough upgrades",
    description: "Buy 40 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 40,
    type: "Purchase Upgrades",
  },
  {
    id: 1050,
    name: "Augmenter",
    description: "Buy 50 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 50,
    type: "Purchase Upgrades",
  },
  {
    id: 1051,
    name: "Mini Upgrader",
    description: "Buy 75 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 75,
    type: "Purchase Upgrades",
  },
  {
    id: 1052,
    name: "Upgrader",
    description: "Buy 100 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 100,
    type: "Purchase Upgrades",
  },
  {
    id: 1053,
    name: "Upgrader II",
    description: "Buy 150 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 150,
    type: "Purchase Upgrades",
  },
  {
    id: 1054,
    name: "Lord of Progress",
    description: "Buy 200 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 200,
    type: "Purchase Upgrades",
  },
  {
    id: 1055,
    name: "Upgrader III",
    description: "Buy 250 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 250,
    type: "Purchase Upgrades",
  },
  {
    id: 1056,
    name: "The full picture",
    description: "Buy 300 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 300,
    type: "Purchase Upgrades",
  },
  {
    id: 1057,
    name: "Upgrader IV",
    description: "Buy 350 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 350,
    type: "Purchase Upgrades",
  },
  {
    id: 1058,
    name: "When there's nothing left to add",
    description: "Buy 400 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 400,
    type: "Purchase Upgrades",
  },
  {
    id: 1059,
    name: "Upgrader V",
    description: "Buy 450 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 450,
    type: "Purchase Upgrades",
  },
  {
    id: 1060,
    name: "Kaizen",
    description: "Buy 500 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 500,
    type: "Purchase Upgrades",
  },
  {
    id: 1061,
    name: "Upgrader VI",
    description: "Buy 550 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 550,
    type: "Purchase Upgrades",
  },
  {
    id: 1062,
    name: "Beyond quality",
    description: "Buy 600 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 600,
    type: "Purchase Upgrades",
  },
  {
    id: 1063,
    name: "Upgrader VII",
    description: "Buy 650 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 650,
    type: "Purchase Upgrades",
  },
  {
    id: 1064,
    name: "Oft we mar what's well",
    description: "Buy 700 upgrades",
    achievementType: "Having",
    acquired: false,
    condition: 700,
    type: "Purchase Upgrades",
  },
];
