import { AchievementType } from "../Cliker";

export const WizardTowerAchievements: AchievementType[] = [
  {
    id: 247,
    name: "Bewitched",
    description: "Have 1 wizard tower",
    condition: 1,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 248,
    name: "The sorcerer's apprentice",
    description: "Have 50 wizard towers",
    condition: 50,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 249,
    name: "Charms and enchantments",
    description: "Have 100 wizard towers",
    condition: 100,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 250,
    name: "Curses and maledictions",
    description: "Have 150 wizard towers",
    condition: 150,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 251,
    name: "Magic kingdom",
    description: "Have 200 wizard towers",
    condition: 200,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 252,
    name: "The wizarding world",
    description: "Have 250 wizard towers",
    condition: 250,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 253,
    name: "And now for my next trick, I'll need a volunteer from the audience",
    description: "Have 300 wizard towers",
    condition: 300,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 254,
    name: "It's a kind of magic",
    description: "Have 350 wizard towers",
    condition: 350,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 255,
    name: "The Prestige",
    description: "Have 400 wizard towers",
    condition: 400,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 256,
    name: "Spell it out for you",
    description: "Have 450 wizard towers",
    condition: 450,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 257,
    name: "The metor men beg to differ",
    description: "Have 500 wizard towers",
    condition: 500,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 258,
    name: "Higtus Figitus migitus mum",
    description: "Have 550 wizard towers",
    condition: 550,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 259,
    name: "Magic thinking",
    description: "Have 600 wizard towers",
    condition: 600,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 260,
    name: "You don't think they could've used... it couldn't have been ma-",
    description: "Have 650 wizard towers",
    condition: 650,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 261,
    name: " Shople Colupis",
    description: "Have 700 wizard towers",
    condition: 700,
    achievementType: "Having",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 262,
    name: "Hocus Pocus",
    description: "Make 10 quintillion cookies just from wizard towers.",
    condition: 1e19,
    achievementType: "Baking",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 263,
    name: "To many rabbits, not enough hats",
    description: "Make 100 septillion cookies just from wizard towers.",
    condition: 1e26,
    achievementType: "Baking",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 264,
    name: "Manafest destiny",
    description: "Make 1 decillion cookies just from wizard towers.",
    condition: 1e33,
    achievementType: "Baking",
    type: "wizardTower",
    acquired: false,
  },
  {
    id: 265,
    name: "TODO",
    description: "TODO",
    condition: 1e96,
    achievementType: "Baking",
    type: "wizardTower",
    acquired: false,
  },
];
