import { AchievementType } from "../Cliker";

export const YouAchievements: AchievementType[] = [
  {
    id: 474,
    name: "My own clone",
    description: "Have 1 You",
    achievementType: "Having",
    acquired: true,
    condition: 1,
    type: "you",
  },
  {
    id: 475,
    name: "Multiplicity",
    description: "Have 50 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 50,
    type: "you",
  },
  {
    id: 476,
    name: "Born for this job",
    description: "Have 100 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 100,
    type: "you",
  },
  {
    id: 477,
    name: "Episode II",
    description: "Have 150 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 150,
    type: "you",
  },
  {
    id: 478,
    name: "Copy that",
    description: "Have 200 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 200,
    type: "you",
  },
  {
    id: 479,
    name: "Life finds a way",
    description: "Have 250 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 250,
    type: "you",
  },
  {
    id: 480,
    name: "Overcrowding",
    description: "Have 300 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 300,
    type: "you",
  },
  {
    id: 481,
    name: "Strength in numbers",
    description: "Have 350 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 350,
    type: "you",
  },
  {
    id: 482,
    name: "Army of me",
    description: "Have 400 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 400,
    type: "you",
  },
  {
    id: 483,
    name: "Know thyself",
    description: "Have 450 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 450,
    type: "you",
  },
  {
    id: 484,
    name: "Didn't maek sense not to live",
    description: "Have 500 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 500,
    type: "you",
  },
  {
    id: 485,
    name: "Genetic bottleneck",
    description: "Have 550 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 550,
    type: "you",
  },
  {
    id: 486,
    name: "Despite everything, it's still you",
    description: "Have 600 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 600,
    type: "you",
  },
  {
    id: 487,
    name: "Everyone everywhere all at once",
    description: "Have 650 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 650,
    type: "you",
  },
  {
    id: 488,
    name: "Introspection",
    description: "Have 700 Yous",
    achievementType: "Having",
    acquired: true,
    condition: 700,
    type: "you",
  },
  {
    id: 489,
    name: "Self-made",
    description: "Make 10 nonillion cookies just from You.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e31,
    type: "you",
  },
  {
    id: 490,
    name: "Reproducible results",
    description: "Make 100 undecillion cookies just from You.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e38,
    type: "you",
  },
  {
    id: 491,
    name: "That's all you",
    description: "Make 1 quattuordecillion cookies just from You.",
    achievementType: "Baking",
    acquired: true,
    condition: 1e45,
    type: "you",
  },
];
