import { UpgradeType } from "../Cliker";

export const ChanceMakersUpgrades: { [key: string]: UpgradeType } = {
  "1200": {
    id: 1200,
    name: "Your lucky cookie",
    description: "Chancemakers are twice as efficient.",
    cost: {
      cookies: 2.6e17,
    },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1201": {
    id: 1201,
    name: "All Bets Are Off",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e17 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1202": {
    id: 1202,
    name: "Winning Lottery Ticket",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e18 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1203": {
    id: 1203,
    name: "Four-Leaf Clover Field",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e20 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1204": {
    id: 1204,
    name: "A Recipe Book About Books",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e22 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "1205": {
    id: 1205,
    name: "Leprechaun Village",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e24 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "1206": {
    id: 1206,
    name: "Improbability Drive",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e27 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1207": {
    id: 1207,
    name: "Antisuperstistronics",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e30 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1208": {
    id: 1208,
    name: "Bunnypedes",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e33 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1209": {
    id: 1209,
    name: "Revised probabilistics",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e36 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1210": {
    id: 1210,
    name: "0-sided dice",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e39 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1211": {
    id: 1211,
    name: "A touch of determinism",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e42 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1212": {
    id: 1212,
    name: "On a streak",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e45 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1213": {
    id: 1213,
    name: "Silver lining maximization",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e48 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1214": {
    id: 1214,
    name: "Gambler's fallacy fallacy",
    description: "Chancemakers are twice as efficient.",
    cost: { cookies: 13e51 },
    acquired: false,
    type: "chancemaker",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
