import { UpgradeType } from "../Cliker";

export const ClickingUpgrades: UpgradeType[] = [
  {
    id: 1100,
    name: "Plastic mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: {
      cookies: 50_000,
    },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1000,
    tier: "Plain",
  },
  {
    id: 1101,
    name: "Iron mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5_000_000 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 100_000,
    tier: "Berrylium",
  },
  {
    id: 1102,
    name: "Titanium mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 500_000_000 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 10_000_000,
    tier: "Blueberrylium",
  },
  {
    id: 1103,
    name: "Adamantium mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 50_000_000_000 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1_000_000_000,
    tier: "Chalcedhoney",
  },
  {
    id: 1104,
    name: "Unobtainium mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e12 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 100_000_000_000,
    tier: "Buttergold",
  },
  {
    id: 1105,
    name: "Eludium mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e14 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 10_000_000_000_000,
    tier: "Sugarmuck",
  },
  {
    id: 1106,
    name: "Wishalloy mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e16 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e15,
    tier: "Jetmint",
  },
  {
    id: 1107,
    name: "Fantasteel mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e18 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e17,
    tier: "Cherrysilver",
  },
  {
    id: 1108,
    name: "Nevercrack mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e20 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e19,
    tier: "Hazelrald",
  },
  {
    id: 1109,
    name: "Armythril mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e22 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e21,
    tier: "Mooncandy",
  },
  {
    id: 1110,
    name: "Technobsidian mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e24 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e23,
    tier: "Astrofudge",
  },
  {
    id: 1111,
    name: "Plasmarble mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e26 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e25,
    tier: "Alabascream",
  },
  {
    id: 1112,
    name: "Miraculite mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e28 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e27,
    tier: "Iridyum",
  },
  {
    id: 1113,
    name: "Aetherice mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e30 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e29,
    tier: "Glucosmium",
  },
  {
    id: 1114,
    name: "	Omniplast mouse",
    description: "Clicking gains +1% of your CpS.",
    cost: { cookies: 5e32 },
    multiplier: 0.01,
    type: "clicking",
    acquired: false,
    requirement: 1e31,
    tier: "Glimmeringue",
  },
];
