import { UpgradeType } from "../Cliker";

export const CortexBakerUpgrades: { [key: string]: UpgradeType } = {
  "1600": {
    id: 1600,
    name: "Principled neural shackles",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 19e23 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1601": {
    id: 1601,
    name: "Obey",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e23 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1602": {
    id: 1602,
    name: "A sprinkle of irrationality",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e24 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1603": {
    id: 1603,
    name: "Front and back hemispheres",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e26 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1604": {
    id: 1604,
    name: "Neural networking",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e28 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "1605": {
    id: 1605,
    name: "Cosmic brainstorms",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e30 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "1606": {
    id: 1606,
    name: "Megatherapy",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e33 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1607": {
    id: 1607,
    name: "Synaptic lubricant",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e36 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1608": {
    id: 1608,
    name: "Psychokinesis",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e39 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1609": {
    id: 1609,
    name: "Spines",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e42 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1610": {
    id: 1610,
    name: "Neuraforming",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e46 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1611": {
    id: 1611,
    name: "Epistemological trickery",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e50 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1612": {
    id: 1612,
    name: "Every possible idea",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e54 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1613": {
    id: 1613,
    name: "The land of dreams",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e58 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1614": {
    id: 1614,
    name: "Intellectual property theft",
    description: "Cortex Bakers are twice as efficient.",
    cost: { cookies: 95e62 },
    acquired: false,
    type: "cortexBaker",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
