import { UpgradeType } from "../Cliker";

export const FractalEngineUpgrades: { [key: string]: UpgradeType } = {
  "1300": {
    id: 1300,
    name: "Metabakeries",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 3.1e18 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1301": {
    id: 1301,
    name: "Mandelbrown Sugar",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 15.5e18 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1302": {
    id: 1302,
    name: "Fractoids",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 15.5e19 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1303": {
    id: 1303,
    name: "Nested Universe Theory",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 15.5e21 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1304": {
    id: 1304,
    name: "Menger sponge cake",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e23 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  1305: {
    id: 1305,
    name: "One particularly good-humored cow",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e25 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  1306: {
    id: 1306,
    name: "Chocolate ouroboros",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e28 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1307": {
    id: 1307,
    name: "Nested",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e31 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1308": {
    id: 1308,
    name: "Space-filling fibers",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e34 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1309": {
    id: 1309,
    name: "Endless book of prose",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e37 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1310": {
    id: 1310,
    name: "The set of all sets",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e39 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1311": {
    id: 1311,
    name: "This upgrade",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e41 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1312": {
    id: 1312,
    name: "A box",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e43 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1313": {
    id: 1313,
    name: "Multiscale profiling",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e45 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1314": {
    id: 1314,
    name: "The more they stay the same",
    description: "Fractal Engines are twice as efficient.",
    cost: { cookies: 1.55e47 },
    acquired: false,
    type: "fractalEngine",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
