import { UpgradeType } from "../Cliker";

export const IdleverseUpgrades: { [key: string]: UpgradeType } = {
  "1500": {
    id: 1500,
    name: "Manifest destiny",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 1.2e24 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1501": {
    id: 1501,
    name: "The multiverse in a nutshell",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e24 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1502": {
    id: 1502,
    name: "All-conversion",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e25 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1503": {
    id: 1503,
    name: "Multiverse agents",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e27 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1504": {
    id: 1504,
    name: "Escape plan",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e29 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "1505": {
    id: 1505,
    name: "Game design",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e31 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "1506": {
    id: 1506,
    name: "Sandbox universe",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e34 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1507": {
    id: 1507,
    name: "Multiverse wars",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e37 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1508": {
    id: 1508,
    name: "Mobile ports",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e40 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1509": {
    id: 1509,
    name: "Encapsulated  reality",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e43 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1510": {
    id: 1510,
    name: "Extrinsic clicking",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e47 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1511": {
    id: 1511,
    name: "Universal idling",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e51 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1512": {
    id: 1512,
    name: "Break the fifth wall",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e55 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1513": {
    id: 1513,
    name: "Opposite universe",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e59 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1514": {
    id: 1514,
    name: "The other routes to Rome",
    description: "Idleverse is twice as efficient",
    cost: { cookies: 6e63 },
    acquired: false,
    type: "idleverse",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
