import { UpgradeType } from "../Cliker";

export const JavaScriptConsoleUpgrades: { [key: string]: UpgradeType } = {
  "1400": {
    id: 1400,
    name: "The JavaScript Console for Dummies",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 7.1e20 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1401": {
    id: 1401,
    name: "64-bit arrays",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e20 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1402": {
    id: 1402,
    name: "Stack Overflow",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e21 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1403": {
    id: 1403,
    name: "Enterprise compiler",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e23 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1404": {
    id: 1404,
    name: "Syntactic sugar",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e25 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "1405": {
    id: 1405,
    name: "A nice cup of coffee",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e27 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "1406": {
    id: 1406,
    name: "Just-in-time baking",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e30 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1407": {
    id: 1407,
    name: "cookies++",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e33 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1408": {
    id: 1408,
    name: "Software updates",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e36 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1409": {
    id: 1409,
    name: "Game.Loop",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e39 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1410": {
    id: 1410,
    name: "Eval()",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e44 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1411": {
    id: 1411,
    name: "Your biggest fans",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e46 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1412": {
    id: 1412,
    name: "Hacker shades",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e49 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1413": {
    id: 1413,
    name: "PHP containment vats",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e52 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1414": {
    id: 1414,
    name: "Simulation failsafes",
    description: "JavaScript Consoles are twice as efficient.",
    cost: { cookies: 3.55e55 },
    acquired: false,
    type: "javascriptConsole",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
