import { UpgradeType } from "../Cliker";

export const KittensUpgrades: UpgradeType[] = [
  {
    id: 999,
    name: "Kitten helpers",
    description: "You gain more CpS the more milk you have.",
    cost: {
      cookies: 9_000_000,
    },
    multiplier: 0.1,
    type: "kittens",
    acquired: false,
    requirement: 13,
    tier: "Plain",
  },
  {
    id: 1000,
    name: "Kitten workers",
    description: "You gain more CpS the more milk you have.",
    cost: {
      cookies: 9_000_000_000,
    },
    multiplier: 0.125,
    type: "kittens",
    acquired: false,
    requirement: 25,
    tier: "Berrylium",
  },
  {
    id: 1001,
    name: "Kitten engineers",
    description: "You gain more CpS the more milk you have.",
    cost: {
      cookies: 90_000_000_000_000,
    },
    multiplier: 0.15,
    type: "kittens",
    acquired: false,
    requirement: 50,

    tier: "Blueberrylium",
  },
  {
    id: 1002,
    name: "Kitten overseers",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 90e15 },
    multiplier: 0.175,
    type: "kittens",
    acquired: false,
    requirement: 75,
    tier: "Chalcedhoney",
  },
  {
    id: 1003,
    name: "Kitten managers",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e18 },
    multiplier: 0.2,
    type: "kittens",
    acquired: false,
    requirement: 100,
    tier: "Buttergold",
  },
  {
    id: 1004,
    name: "Kitten accountants",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e21 },
    multiplier: 0.2,
    type: "kittens",
    acquired: false,
    requirement: 125,
    tier: "Sugarmuck",
  },
  {
    id: 1005,
    name: "Kitten specialists",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e24 },
    multiplier: 0.2,
    type: "kittens",
    acquired: false,
    requirement: 150,
    tier: "Jetmint",
  },
  {
    id: 1006,
    name: "Kitten experts",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e27 },
    multiplier: 0.2,
    type: "kittens",
    acquired: false,
    requirement: 175,
    tier: "Cherrysilver",
  },
  {
    id: 1007,
    name: "Kitten consultants",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e30 },
    multiplier: 0.2,
    type: "kittens",
    acquired: false,
    requirement: 200,
    tier: "Hazelrald",
  },
  {
    id: 1008,
    name: "Kitten assistants to the regional manager",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e33 },
    multiplier: 0.175,
    type: "kittens",
    acquired: false,
    requirement: 225,
    tier: "Mooncandy",
  },
  {
    id: 1009,
    name: "Kitten marketeers",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e36 },
    multiplier: 0.15,
    type: "kittens",
    acquired: false,
    requirement: 250,
    tier: "Astrofudge",
  },
  {
    id: 1010,
    name: "Kitten analysts",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e39 },
    multiplier: 0.125,
    type: "kittens",
    acquired: false,
    requirement: 275,
    tier: "Alabascream",
  },
  {
    id: 1011,
    name: "Kitten executives",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e42 },
    multiplier: 0.115,
    type: "kittens",
    acquired: false,
    requirement: 300,
    tier: "Iridyum",
  },
  {
    id: 1012,
    name: "Kitten Admins",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e45 },
    multiplier: 0.11,
    type: "kittens",
    acquired: false,
    requirement: 325,
    tier: "Glucosmium",
  },
  {
    id: 1013,
    name: "Kitten strategists",
    description: "You gain more CpS the more milk you have.",
    cost: { cookies: 900e48 },
    multiplier: 0.105,
    type: "kittens",
    acquired: false,
    requirement: 350,
    tier: "Glimmeringue",
  },
];
