import { UpgradeType } from "../Cliker2";

export const PrismUpgrades: { [key: string]: UpgradeType } = {
  "1": {
    id: 1,
    name: "Gem polish",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 21e15,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "2": {
    id: 2,
    name: "9th color",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 105e15,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "3": {
    id: 3,
    name: "Chocolate light",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 1.05e18,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "4": {
    id: 4,
    name: "Grainbow",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 105e18,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "5": {
    id: 5,
    name: "Pure cosmic light",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 10.5e21,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "6": {
    id: 6,
    name: "Glow-in-the-dark",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 1.05e24,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "7": {
    id: 7,
    name: "Lux sanctorum",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 1.05e27,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "8": {
    id: 8,
    name: "Reverse shadows",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 1.05e30,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "9": {
    id: 9,
    name: "Crystal mirrors",
    description: "Prisms are twice as efficient",
    cost: {
      cookies: 1.05e33,
    },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "10": {
    id: 10,
    name: "Reverse theory of light",
    description: "Prisms are twice as efficient",
    cost: { cookies: 1.05e36 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "11": {
    id: 11,
    name: "Light capture measures",
    description: "Prisms are twice as efficient",
    cost: { cookies: 10.5e39 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "12": {
    id: 12,
    name: "Light speed limit",
    description: "Prisms are twice as efficient",
    cost: { cookies: 1.05e43 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "13": {
    id: 13,
    name: "Occam's laser",
    description: "Prisms are twice as efficient",
    cost: { cookies: 1.05e46 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "14": {
    id: 14,
    name: "Hyperblack Paint",
    description: "Prisms are twice as efficient",
    cost: { cookies: 1.05e49 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "15": {
    id: 15,
    name: "Lab googles but like cool shades",
    description: "Prisms are twice as efficient",
    cost: { cookies: 1.05e52 },
    acquired: false,
    type: "prism",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
