import { UpgradeType } from "../Cliker";

export const YouUpgrades: { [key: string]: UpgradeType } = {
  "1700": {
    id: 1700,
    name: "Cloning  vats",
    description: "You are twice as efficient.",
    cost: { cookies: 5.4e27 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 1,
    tier: "Plain",
  },
  "1701": {
    id: 1701,
    name: "Energized nutrients",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e28 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 5,
    tier: "Berrylium",
  },
  "1702": {
    id: 1702,
    name: "Stunt doubles",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e29 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 25,
    tier: "Blueberrylium",
  },
  "1703": {
    id: 1703,
    name: "Clone recycling plant",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e31 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 50,
    tier: "Chalcedhoney",
  },
  "1704": {
    id: 1704,
    name: "Free-range clones",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e33 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 100,
    tier: "Buttergold",
  },
  "1705": {
    id: 1705,
    name: "Genetic tailoring",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e35 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 150,
    tier: "Sugarmuck",
  },
  "1706": {
    id: 1706,
    name: "Power in diversity",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e38 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 200,
    tier: "Jetmint",
  },
  "1707": {
    id: 1707,
    name: "Self-betterment",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e41 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 250,
    tier: "Cherrysilver",
  },
  "1708": {
    id: 1708,
    name: "Source control",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e44 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 300,
    tier: "Hazelrald",
  },
  "1709": {
    id: 1709,
    name: "United workforce",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e47 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 350,
    tier: "Mooncandy",
  },
  "1710": {
    id: 1710,
    name: "Safety patrols",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e51 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 400,
    tier: "Astrofudge",
  },
  "1711": {
    id: 1711,
    name: "Clone rights activists",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e55 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 450,
    tier: "Alabascream",
  },
  "1712": {
    id: 1712,
    name: "One big family",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e59 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 500,
    tier: "Iridyum",
  },
  "1713": {
    id: 1713,
    name: "Fine-tuned body plans",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e63 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 550,
    tier: "Glucosmium",
  },
  "1714": {
    id: 1714,
    name: "Reading your clones bedtimes stories",
    description: "You are twice as efficient.",
    cost: { cookies: 2.7e67 },
    acquired: false,
    type: "you",
    multiplier: 2,
    requirement: 600,
    tier: "Glimmeringue",
  },
};
