import { SaveType } from "./ui";

export type Resource = {
  cookies: number;
};
export type BuildingType =
  | "cursor"
  | "grandma"
  | "farm"
  | "mine"
  | "factory"
  | "bank"
  | "temple"
  | "wizardTower"
  | "shipment";
export type UpgradeType = {
  id: number;
  name: string;
  cost: Resource;
  multiplier: number;
  requirement: number;
  acquired: boolean;
  description: string;
  type: BuildingType;
};
export type gameInit = {
  resource: Resource;
  clickResourceGeneration: Resource;
  resourceGeneration: Resource;
};

export type StructureInit = {
  structure: number;
  structureCost: Resource;
  structureCostDefault: Resource;
  structureResourceGeneration: Resource;

  structureResourceGenerationDefault: Resource;
};

export default class Clicker {
  public resource: Resource;
  private lifeTimeCookies: Resource = { cookies: 0 };
  private lifeTimeCookiesClick: Resource = { cookies: 0 };
  private multiplier: number = 100;

  //Building's
  public grandma: Grandma = new Grandma(this);
  public autoClicker: Cursor = new Cursor(this);
  public farm: Farm = new Farm(this);
  public mine: Mine = new Mine(this);
  public factory: Factory = new Factory(this);
  public bank: Bank = new Bank(this);
  public temple: Temple = new Temple(this);
  public wizardTower: WizardTower = new WizardTower(this);
  public shipment: Shipment = new Shipment(this);

  // Generation
  private clickResourceGeneration: Resource;
  private resourceGeneration: Resource;

  constructor(
    { resource, clickResourceGeneration, resourceGeneration }: gameInit = {
      resource: {
        cookies: 0,
      } as Resource,
      clickResourceGeneration: { cookies: 1 } as Resource,
      resourceGeneration: {
        cookies: 0,
      } as Resource,
    }
  ) {
    this.resource = resource;
    this.clickResourceGeneration = clickResourceGeneration;
    this.resourceGeneration = resourceGeneration;

    // this.autoClicker = autoClicker;
    this.PassiveCalculateResourceGeneration();
    this.initialize();
  }
  //Initialize (game context inside each building)
  private initialize(): void {
    this.autoClicker = new Cursor(this);
    this.grandma = new Grandma(this);
    this.farm = new Farm(this);
    this.mine = new Mine(this);
    this.factory = new Factory(this);
    this.bank = new Bank(this);
    this.temple = new Temple(this);
    this.wizardTower = new WizardTower(this);
    this.shipment = new Shipment(this);
  }

  // Calculate how many cookies per second are generated by all structures
  //TODO: Need to be improved
  private PassiveCalculateResourceGeneration(): void {
    this.autoClicker.calculateStructureResourceGeneration1();
    this.grandma.calculateStructureResourceGeneration1();
    this.farm.calculateStructureResourceGeneration1();
    this.mine.calculateStructureResourceGeneration1();
    this.factory.calculateStructureResourceGeneration1();
    this.bank.calculateStructureResourceGeneration1();
    this.temple.calculateStructureResourceGeneration1();
    this.wizardTower.calculateStructureResourceGeneration1();
    this.shipment.calculateStructureResourceGeneration1();

    this.resourceGeneration.cookies = 0;
    const Structs: Resource[] = [];
    // Required to Add more Structures
    Structs.push(this.grandma.getStructureResourceGeneration());
    Structs.push(this.autoClicker.getStructureResourceGeneration());
    Structs.push(this.farm.getStructureResourceGeneration());
    Structs.push(this.mine.getStructureResourceGeneration());
    Structs.push(this.factory.getStructureResourceGeneration());
    Structs.push(this.bank.getStructureResourceGeneration());
    Structs.push(this.temple.getStructureResourceGeneration());
    Structs.push(this.wizardTower.getStructureResourceGeneration());
    Structs.push(this.shipment.getStructureResourceGeneration());
    Structs.forEach((struct) => {
      this.resourceGeneration.cookies += struct.cookies;
    });
    this.ClickCalculateResourceGeneration();
  }

  // Calculate how many cookies per click are generated
  public ClickCalculateResourceGeneration(): void {
    let start = 1;

    this.autoClicker.cursorUpgrades.forEach((upgrade) => {
      if (upgrade.acquired && upgrade.id !== 4) {
        start *= upgrade.multiplier;
      } else if (upgrade.acquired && upgrade.id === 4) {
        start += upgrade.multiplier * this.autoClicker.getNoneCursorAmount();
      }
    });

    this.clickResourceGeneration.cookies = start;
  }

  // Getters
  public getClickResourceGeneration(): Resource {
    return this.clickResourceGeneration;
  }

  public getPassiveResourceGeneration(): Resource {
    return this.resourceGeneration;
  }
  //Methods here to be deleted
  // Grandma
  public buyGrandma(): void {
    this.grandma.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }

  // AutoClicker
  public buyAutoClicker(): void {
    this.autoClicker.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }

  // Farm
  public buyFarm(): void {
    this.farm.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }

  // Mine
  public buyMine(): void {
    this.mine.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }
  // Factory
  public buyFactory(): void {
    this.factory.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }
  // Bank
  public buyBank(): void {
    this.bank.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }
  // Temple
  public buyTemple(): void {
    this.temple.increaseStructure(this.resource);
    this.PassiveCalculateResourceGeneration();
  }

  // WizardTower Unused
  // public buyWizardTower(): void {
  //   this.wizardTower.increaseStructure(this.resource);
  //   this.PassiveCalculateResourceGeneration();
  // }
  // ----------To be deleted end--------
  public buyBuilding(type: BuildingType, amount: number = 1): void {
    if (type === "cursor") {
      this.autoClicker.increaseStructure(this.resource, amount);
    }
    if (type === "grandma") {
      this.grandma.increaseStructure(this.resource, amount);
    }
    if (type === "farm") {
      this.farm.increaseStructure(this.resource, amount);
    }
    if (type === "mine") {
      this.mine.increaseStructure(this.resource, amount);
    }
    if (type === "factory") {
      this.factory.increaseStructure(this.resource, amount);
    }
    if (type === "bank") {
      this.bank.increaseStructure(this.resource, amount);
    }
    if (type === "temple") {
      this.temple.increaseStructure(this.resource, amount);
    }
    if (type === "wizardTower") {
      this.wizardTower.increaseStructure(this.resource, amount);
    }
    if (type === "shipment") {
      this.shipment.increaseStructure(this.resource, amount);
    }
    this.PassiveCalculateResourceGeneration();
  }
  // Method Called by clock and click to increase resource(cookies)
  public increaseResource(addValue: Resource): void {
    this.resource.cookies += (addValue.cookies * this.multiplier) / 100;
    this.lifeTimeCookies.cookies += (addValue.cookies * this.multiplier) / 100;
    this.autoClicker.gameTick(this.multiplier);
    this.grandma.gameTick(this.multiplier);
    this.farm.gameTick(this.multiplier);
    this.mine.gameTick(this.multiplier);
    this.factory.gameTick(this.multiplier);
    this.bank.gameTick(this.multiplier);
    this.temple.gameTick(this.multiplier);
    this.wizardTower.gameTick(this.multiplier);
    this.shipment.gameTick(this.multiplier);
  }
  public increaseResourceClick(addValue: Resource): void {
    this.resource.cookies += (addValue.cookies * this.multiplier) / 100;
    this.lifeTimeCookies.cookies += (addValue.cookies * this.multiplier) / 100;
    this.lifeTimeCookiesClick.cookies +=
      (addValue.cookies * this.multiplier) / 100;
  }

  // Buy an Upgrade for a Structure (Grandma, AutoClicker, Farm, Mine...)
  public buyStructureUpgrade(id: number, type: string): void {
    if (type === "cursor") {
      this.autoClicker.buyUpgradeLevel(this.resource, id);
    }
    if (type === "grandma") {
      this.grandma.buyUpgradeLevel(this.resource, id);
    }
    if (type === "farm") {
      this.farm.buyUpgradeLevel(this.resource, id);
    }
    if (type === "mine") {
      this.mine.buyUpgradeLevel(this.resource, id);
    }
    if (type === "factory") {
      this.factory.buyUpgradeLevel(this.resource, id);
    }
    if (type === "bank") {
      this.bank.buyUpgradeLevel(this.resource, id);
    }
    if (type === "temple") {
      this.temple.buyUpgradeLevel(this.resource, id);
    }
    if (type === "wizardTower") {
      this.wizardTower.buyUpgradeLevel(this.resource, id);
    }
    if (type === "shipment") {
      this.shipment.buyUpgradeLevel(this.resource, id);
    }
    this.PassiveCalculateResourceGeneration();
  }

  // Check if the player can buy an upgrade for a structure
  public canBuyStructureUpgrade(id: number, type: String): boolean {
    if (type === "cursor") {
      return this.autoClicker.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "grandma") {
      return this.grandma.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "farm") {
      return this.farm.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "mine") {
      return this.mine.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "factory") {
      return this.factory.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "bank") {
      return this.bank.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "temple") {
      return this.temple.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "wizardTower") {
      return this.wizardTower.canBuyStructureUpgrade(this.resource, id);
    }
    if (type === "shipment") {
      return this.shipment.canBuyStructureUpgrade(this.resource, id);
    }
    return false;
  }

  // Getters Resource
  public get_resources(): Resource {
    return this.resource;
  }
  public get_string_Number(): string {
    return Math.floor(this.resource.cookies).toString();
  }

  public get_lifeTimeCookies(): Resource {
    return this.lifeTimeCookies;
  }

  // Get the list of possible upgrades for all structures
  public getPossibleUpgradeList(): UpgradeType[] {
    const list: UpgradeType[] = [
      ...this.autoClicker.getUpgradesInRange(),
      ...this.grandma.getUpgradesInRange(),
      ...this.farm.getUpgradesInRange(),
      ...this.mine.getUpgradesInRange(),
      ...this.factory.getUpgradesInRange(),
      ...this.bank.getUpgradesInRange(),
      ...this.temple.getUpgradesInRange(),
      ...this.wizardTower.getUpgradesInRange(),
      ...this.shipment.getUpgradesInRange(),
    ].sort((a, b) => {
      return a.cost.cookies - b.cost.cookies;
    });

    return list;
  }

  // Save Game to LocalStorage (not Stable)
  public SaveGame() {
    let save = {
      resource: this.resource,
      lifeTimeCookies: this.lifeTimeCookies,
      multiplier: this.multiplier,
      grandma: {
        structure: this.grandma.structure,
        structureCost: this.grandma.structureCost,
        lifeTimeCookiesBuilding: this.grandma.lifeTimeCookiesBuilding,
        grandmaUpgrades: Object.fromEntries(this.grandma.grandmaUpgrades),
      },
      autoClicker: {
        structure: this.autoClicker.structure,
        structureCost: this.autoClicker.structureCost,
        lifeTimeCookiesBuilding: this.autoClicker.lifeTimeCookiesBuilding,
        cursorUpgrades: Object.fromEntries(this.autoClicker.cursorUpgrades),
      },
      farm: {
        structure: this.farm.structure,
        structureCost: this.farm.structureCost,
        lifeTimeCookiesBuilding: this.farm.lifeTimeCookiesBuilding,
        farmUpgrades: Object.fromEntries(this.farm.farmUpgrades),
      },
      mine: {
        structure: this.mine.structure,
        structureCost: this.mine.structureCost,
        lifeTimeCookiesBuilding: this.mine.lifeTimeCookiesBuilding,
        mineUpgrades: Object.fromEntries(this.mine.mineUpgrades),
      },
      factory: {
        structure: this.factory.structure,
        structureCost: this.factory.structureCost,
        lifeTimeCookiesBuilding: this.factory.lifeTimeCookiesBuilding,
        factoryUpgrades: Object.fromEntries(this.factory.factoryUpgrades),
      },
      bank: {
        structure: this.bank.structure,
        structureCost: this.bank.structureCost,
        lifeTimeCookiesBuilding: this.bank.lifeTimeCookiesBuilding,
        bankUpgrades: Object.fromEntries(this.bank.bankUpgrades),
      },
      temple: {
        structure: this.temple.structure,
        structureCost: this.temple.structureCost,
        lifeTimeCookiesBuilding: this.temple.lifeTimeCookiesBuilding,
        templeUpgrades: Object.fromEntries(this.temple.templeUpgrades),
      },
      wizardTower: {
        structure: this.wizardTower.structure,
        structureCost: this.wizardTower.structureCost,
        lifeTimeCookiesBuilding: this.wizardTower.lifeTimeCookiesBuilding,
        wizardTowerUpgrades: Object.fromEntries(
          this.wizardTower.WizardTowerUpgrades
        ),
      },
      shipment: {
        structure: this.shipment.structure,
        structureCost: this.shipment.structureCost,
        lifeTimeCookiesBuilding: this.shipment.lifeTimeCookiesBuilding,
        shipmentUpgrades: Object.fromEntries(this.shipment.shipmentUpgrades),
      },
    };
    return save;
  }

  // Load Game from LocalStorage (not Stable)
  //TODO: Type Save
  public LoadGame(save: SaveType) {
    // Set Cookies
    this.resource = save.resource;
    this.lifeTimeCookies = save.lifeTimeCookies;
    this.multiplier = save.multiplier ?? 100;
    // Set the Grandma
    this.grandma.structureCost = save.grandma.structureCost;
    this.grandma.structure = save.grandma.structure;
    this.grandma.lifeTimeCookiesBuilding = save.grandma
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.grandma.grandmaUpgrades = new Map(
      Object.entries(save.grandma.grandmaUpgrades)
    );
    this.grandma.calculateStructureResourceGeneration1();
    // Set the Cursor
    this.autoClicker.structureCost = save.autoClicker.structureCost;
    this.autoClicker.structure = save.autoClicker.structure;
    this.autoClicker.lifeTimeCookiesBuilding = save.autoClicker
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.autoClicker.cursorUpgrades = new Map(
      Object.entries(save.autoClicker.cursorUpgrades)
    );
    this.autoClicker.calculateStructureResourceGeneration1();
    // Set the farm
    this.farm.structureCost = save.farm.structureCost;
    this.farm.structure = save.farm.structure;
    this.farm.lifeTimeCookiesBuilding = save.farm.lifeTimeCookiesBuilding ?? {
      cookies: 0,
    };
    this.farm.farmUpgrades = new Map(Object.entries(save.farm.farmUpgrades));
    this.farm.calculateStructureResourceGeneration1();
    // Set the mine
    this.mine.structureCost = save.mine.structureCost;
    this.mine.structure = save.mine.structure;
    this.mine.lifeTimeCookiesBuilding = save.mine.lifeTimeCookiesBuilding ?? {
      cookies: 0,
    };
    this.mine.mineUpgrades = new Map(Object.entries(save.mine.mineUpgrades));
    this.mine.calculateStructureResourceGeneration1();

    // Set the factory
    this.factory.structureCost = save.factory.structureCost;
    this.factory.structure = save.factory.structure;
    this.factory.lifeTimeCookiesBuilding = save.factory
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.factory.factoryUpgrades = new Map(
      Object.entries(save.factory.factoryUpgrades)
    );
    this.factory.calculateStructureResourceGeneration1();

    // Set the bank
    this.bank.structureCost = save.bank.structureCost;
    this.bank.structure = save.bank.structure;
    this.bank.lifeTimeCookiesBuilding = save.bank.lifeTimeCookiesBuilding ?? {
      cookies: 0,
    };
    this.bank.bankUpgrades = new Map(Object.entries(save.bank.bankUpgrades));
    this.bank.calculateStructureResourceGeneration1();

    // Set the temple
    this.temple.structureCost = save.temple.structureCost;
    this.temple.structure = save.temple.structure;
    this.temple.lifeTimeCookiesBuilding = save.temple
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.temple.templeUpgrades = new Map(
      Object.entries(save.temple.templeUpgrades)
    );
    this.temple.calculateStructureResourceGeneration1();

    // Set the wizardTower
    this.wizardTower.structureCost = save.wizardTower.structureCost;
    this.wizardTower.structure = save.wizardTower.structure;
    this.wizardTower.lifeTimeCookiesBuilding = save.wizardTower
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.wizardTower.WizardTowerUpgrades = new Map(
      Object.entries(save.wizardTower.wizardTowerUpgrades)
    );
    this.wizardTower.calculateStructureResourceGeneration1();

    // Set the shipment
    this.shipment.structureCost = save.shipment.structureCost;
    this.shipment.structure = save.shipment.structure;
    this.shipment.lifeTimeCookiesBuilding = save.shipment
      .lifeTimeCookiesBuilding ?? { cookies: 0 };
    this.shipment.shipmentUpgrades = new Map(
      Object.entries(save.shipment.shipmentUpgrades)
    );
    // Reload Game generation
    this.PassiveCalculateResourceGeneration();
    this.ClickCalculateResourceGeneration();
  }
  public resetGame(): void {
    this.resource = { cookies: 0 };
    this.lifeTimeCookies = { cookies: 0 };
    this.multiplier = 100;
    this.grandma = new Grandma(this);
    this.autoClicker = new Cursor(this);
    this.farm = new Farm(this);
    this.mine = new Mine(this);
    this.factory = new Factory(this);
    this.bank = new Bank(this);
    this.temple = new Temple(this);
    this.wizardTower = new WizardTower(this);
    this.shipment = new Shipment(this);
    this.PassiveCalculateResourceGeneration();
    this.ClickCalculateResourceGeneration();
  }
}
class Global {
  //Help Function to update the cost of the upgrade
  public updateCost(
    currentCost: Resource,
    base: Resource,
    totalBuilding: number
  ): Resource {
    currentCost.cookies = base.cookies * 1.15 ** totalBuilding;
    return currentCost;
  }
  //Help Function to check if the player can buy the upgrade

  //Help Function to buy the upgrade or structure
  public buyUpgrade(cost: number, cookies: Resource): void {
    cookies.cookies -= cost;
  }
  //Help Function to convert the resource to a string
  public ResourceToString(resource: Resource): string {
    return Math.floor(resource.cookies).toString();
  }
}

export class Structure extends Global {
  public canBuy(cookies: Resource, amount: number = 1): boolean {
    if (amount === 1) {
      if (cookies.cookies > this.structureCost.cookies) {
        return true;
      }
    } else {
      let total = 0;
      for (let i = 0; i < amount; i++) {
        total += this.checkFutureCost(i);
      }
      if (cookies.cookies > total) {
        return true;
      } else {
        return false;
      }
    }

    return false;
  }

  public checkFutureCost(amount: number): number {
    if (amount === 0) {
      return this.structureCost.cookies;
    }
    let currentCostTemp =
      this.structureCostDefault.cookies * 1.15 ** (this.structure + amount);

    return currentCostTemp;
  }
  //How many of this Building the player has.
  public structure: number;

  //The cost of the next Building
  public structureCost: Resource;

  //How much the Building generates per second
  public structureResourceGeneration: Resource;

  //The default cost of the Building
  private structureCostDefault: Resource;
  //The default generation of the Building
  public structureResourceGenerationDefault: Resource;
  public lifeTimeCookiesBuilding: { cookies: number } = { cookies: 0 };
  constructor({
    structure,
    structureCost,
    structureCostDefault,
    structureResourceGeneration,
    structureResourceGenerationDefault,
  }: StructureInit) {
    super();
    this.structure = structure;
    this.structureCost = structureCost;
    this.structureCostDefault = structureCostDefault;
    this.structureResourceGeneration = structureResourceGeneration;
    this.structureResourceGenerationDefault =
      structureResourceGenerationDefault;
  }

  //Buy a structure
  public increaseStructure(cookies: Resource, amount: number = 1): void {
    if (this.canBuy(cookies, amount)) {
      this.buyUpgrade(this.getStructureCost(amount).cookies, cookies);
      this.structure += amount;
      this.increaseStructureCost();
    }
  }
  //
  public gameTick(multiplier: number): void {
    this.lifeTimeCookiesBuilding.cookies +=
      (this.getStructureResourceGeneration().cookies * multiplier) / 100 / 5;
  }
  public getLifeTimeCookiesBuilding(): number {
    return this.lifeTimeCookiesBuilding.cookies;
  }

  //Update the cost of the structure after buying one
  private increaseStructureCost(): void {
    this.structureCost = this.updateCost(
      this.structureCost,
      this.structureCostDefault,
      this.structure
    );
  }

  //Get the Total generation of the buildings of this type  (structure * generation)
  public getStructureResourceGeneration(): Resource {
    return {
      cookies: this.structureResourceGeneration.cookies * this.structure,
    };
  }

  //Get Cost of the next structure
  public getStructureCost(amount: number = 1): Resource {
    if (amount === 1) {
      return this.structureCost;
    }
    let total = 0;
    for (let i = 0; i < amount; i++) {
      total += this.checkFutureCost(i);
    }
    return { cookies: total };
  }

  //Get the cost of the next structure as a string
  public getStructureCostString(): string {
    return this.ResourceToString(this.structureCost);
  }

  // If the player can buy the structure
  public canBuyStructure(cookies: Resource): boolean {
    return this.canBuy(cookies);
  }

  //Get the generation of the structure as a string
  public getBuildingCPS(): string {
    return (this.structureResourceGeneration.cookies * this.structure).toFixed(
      2
    );
  }
  //Get the amount of the Buildings
  public getStructureAmount(): number {
    return this.structure;
  }
}

class Cursor extends Structure {
  public cursorUpgrades1 = {
    "1": {
      id: 1,
      description: `The mouse and cursors are twice as efficient.
      "prod prod"`,
      name: "Reinforced Index Finger",
      cost: { cookies: 100 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "2": {
      id: 2,
      name: "Carpal Tunnel Prevention Cream",
      description: `The mouse and cursors are twice as efficient.
      "it... it hurts to click..."`,
      cost: { cookies: 500 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "3": {
      id: 3,
      name: "Ambidextrous",
      description: `The mouse and cursors are twice as efficient.
      "Look ma, both hands!"`,
      cost: { cookies: 10000 },
      multiplier: 2,
      requirement: 10,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "4": {
      id: 4,
      name: "Thousand Fingers",
      description: `The mouse and cursors gain +0.1 cookies for each non-cursor object owned.`,
      cost: { cookies: 100000 },
      multiplier: 0.1, // This requires a special function to check every Building that exists
      requirement: 25,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "5": {
      id: 5,
      name: "Million Fingers",
      description: `Multiplies the gain from Thousand fingers by 5.
      "clickityclickity"`,
      cost: { cookies: 10000000 },
      multiplier: 5, // Increase the first 1000 cursor by 5?
      requirement: 50,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "6": {
      id: 6,
      name: "Billion Fingers",
      description: `Multiplies the gain from Thousand fingers by 10.`,
      cost: { cookies: 1000000000 },
      multiplier: 10, // Increase the first 1000 cursor by 10?
      requirement: 100,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "7": {
      id: 7,
      name: "Trillion Fingers",
      cost: { cookies: 100000000000 },
      description: `Multiplies the gain from Thousand fingers by 20.`,
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 150,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "8": {
      id: 8,
      name: "Quadrillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 10000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 200,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "9": {
      id: 9,
      name: "Quintillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 1000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 250,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "10": {
      id: 10,
      name: "Sextillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 100000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 300,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "11": {
      id: 11,
      name: "Septillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 10000000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 350,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "12": {
      id: 12,
      name: "Octillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 1000000000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 400,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "13": {
      id: 13,
      name: "Nonillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 100000000000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 450,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "14": {
      id: 14,
      name: "Decillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 10000000000000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 500,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
    "15": {
      id: 15,
      name: "Undecillion Fingers",
      description: `Multiplies the gain from Thousand fingers by 20.`,
      cost: { cookies: 1000000000000000000000000000 },
      multiplier: 20, // Increase the first 1000 cursor by 20?
      requirement: 550,
      acquired: false,
      type: "cursor",
    } as UpgradeType,
  };
  public cursorUpgrades = new Map(Object.entries(this.cursorUpgrades1));
  private game: Clicker;
  // Constructor Needs to be fixed to Allow for Saving
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 15 },
      structureResourceGeneration: { cookies: 0.0 },
      structureResourceGenerationDefault: { cookies: 0.1 },

      structureCostDefault: { cookies: 15 },
    });
    this.game = game;
    this.calculateStructureResourceGeneration1();
  }
  public getUpgradesInRange(): UpgradeType[] {
    const list: UpgradeType[] = [];
    this.cursorUpgrades.forEach((value, key) => {
      if (this.getStructureAmount() >= value.requirement && !value.acquired) {
        list.push(value);
      }
    });
    return list;
  }
  // Needs Requirements Check TODO
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const nextUpgrade = this.cursorUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return;
    }
    if (!this.canBuyStructureUpgrade(cookies, id)) {
      return;
    }
    cookies.cookies = cookies.cookies - nextUpgrade.cost.cookies;
    nextUpgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  // Fix name after a concrete Plan
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.cursorUpgrades.forEach((value, key) => {
      if (value.acquired && value.id !== 4) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      } else if (value.acquired && value.id === 4) {
        this.structureResourceGeneration.cookies +=
          value.multiplier * this.getNoneCursorAmount();
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.cursorUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.cursorUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
  // This Function needs to be updated
  // TODO: Update this function as buildings are added
  public getNoneCursorAmount(): number {
    let amount = 0;
    amount += this.game.grandma.getStructureAmount();
    amount += this.game.farm.getStructureAmount();
    amount += this.game.mine.getStructureAmount();
    amount += this.game.factory.getStructureAmount();
    amount += this.game.bank.getStructureAmount();
    amount += this.game.temple.getStructureAmount();
    amount += this.game.wizardTower.getStructureAmount();
    amount += this.game.shipment.getStructureAmount();
    return amount;
  }
}

class Grandma extends Structure {
  public grandmaUpgrades1: { [key: string]: UpgradeType } = {
    "16": {
      id: 16,
      name: "Forwards from grandma",
      description: `Grandmas are twice as efficient.
      "RE:RE:thought you'd get a kick out of this ;))"`,
      cost: { cookies: 1000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "grandma",
    },
    "17": {
      id: 17,
      name: "Steel-plated rolling pins",
      description: `Grandmas are twice as efficient.
      "Just what you kneaded."`,
      cost: { cookies: 5000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "grandma",
    },
    "18": {
      id: 18,
      name: "Lubricated dentures",
      description: `Grandmas are twice as efficient.
      "squish"`,
      cost: { cookies: 50000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "grandma",
    },
    "19": {
      id: 19,
      name: "Prune juice",
      cost: { cookies: 5_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Gets me going."`,
    },
    "20": {
      id: 20,
      name: "Double-thick glasses",
      cost: { cookies: 500_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Oh... so THAT's what I've been baking."`,
    },
    "21": {
      id: 21,
      name: "Aging agents",
      cost: { cookies: 50_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Counter-intuitively, grandmas have the uncanny ability to become more powerful the older they get."`,
    },
    "22": {
      id: 22,
      name: "Xtreme walkers",
      cost: { cookies: 50_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Complete with flame decals and a little horn that goes "toot"."`,
    },
    "23": {
      id: 23,
      name: "The Unbridling",
      cost: { cookies: 50_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "It might be a classic tale of bad parenting, but let's see where grandma is going with this."`,
    },
    "24": {
      id: 24,
      name: "Reverse dementia",
      cost: { cookies: 50_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Extremely unsettling, and somehow even worse than the regular kind."`,
    },
    "25": {
      id: 25,
      name: "Timeproof hair dyes",
      cost: { cookies: 50_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Why do they always have those strange wispy pink dos? What do they know about candy floss that we don't?"`,
    },
    "26": {
      id: 26,
      name: "Good manners",
      cost: { cookies: 50_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Apparently these ladies are much more amiable if you take the time to learn their strange, ancient customs, which seem to involve saying "please" and "thank you" and staring at the sun with bulging eyes while muttering eldritch curses under your breath."`,
    },
    "27": {
      id: 27,
      name: "Generation degeneration",
      cost: { cookies: 50_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Genetic testing shows that most of your grandmas are infected with a strange degenerative disease that only seems to further their powers; the more time passes, the older they get. This should concern you."`,
    },
    "28": {
      id: 28,
      name: "Visits",
      cost: { cookies: 50_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "In an extensive double-blind study (sample size: 12 millions), your researchers have found evidence that grandmas are up to twice as productive if you just come by and say hi once in a while. It's nice to check up on your grans! (Do not under any circumstances ingest any tea or tea-like substances the grandmas may offer you.)."`,
    },
    "29": {
      id: 29,
      name: "Kitchen cabinets",
      cost: { cookies: 50_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "A grandma's kitchen cabinet is a befuddling place. Through lesser-studied aggregating instincts, grandmas will tend to gradually fill all nearby cabinets with various sorts of things, such as curious coconut snacks or dietetic powders. By contract, these are legally yours, which opens up exciting opportunities for your substance investigation department."`,
    },
    "30": {
      id: 30,
      name: "Foam-tipped canes",
      cost: { cookies: 50_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "grandma",
      description: `Grandmas are twice as efficient.
      "Perhaps the result of prolonged service, your grandmas have developed all kinds of odd and aggressive hierarchies among themselves; these will help them not hurt each other as bad during their endless turf wars."`,
    },
  };
  public grandmaUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.grandmaUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 100 },
      structureResourceGeneration: { cookies: 1 },
      structureResourceGenerationDefault: { cookies: 1 },

      structureCostDefault: { cookies: 100 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.grandmaUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.grandmaUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.grandmaUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.grandmaUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.grandmaUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

class Farm extends Structure {
  public farmUpgrades1: { [key: string]: UpgradeType } = {
    "31": {
      id: 31,
      name: "Cheap hoes",
      cost: { cookies: 11_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Rake in the dough!"`,
    },
    "32": {
      id: 32,
      name: "Fertilizer",
      cost: { cookies: 55_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "It's chocolate, I swear."`,
    },
    "33": {
      id: 33,
      name: "Cookie trees",
      cost: { cookies: 550_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "A relative of the breadfruit."`,
    },
    "34": {
      id: 34,
      name: "Genetically-modified cookies",
      cost: { cookies: 55_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "All-natural mutations."`,
    },
    "35": {
      id: 35,
      name: "Gingerbread scarecrows",
      cost: { cookies: 550_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Staring at your crops with mischievous glee."`,
    },
    "36": {
      id: 36,
      name: "Pulsar sprinklers",
      cost: { cookies: 550_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "There's no such thing as over-watering. The moistest is the bestest."`,
    },
    "37": {
      id: 37,
      name: "Fudge fungus",
      cost: { cookies: 550_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "A sugary parasite whose tendrils help cookie growth.
      Please do not breathe in the spores. In case of spore ingestion, seek medical help within the next 36 seconds."`,
    },
    "38": {
      id: 38,
      name: "Wheat triffids",
      cost: { cookies: 550_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Taking care of crops is so much easier when your plants can just walk about and help around the farm.
      Do not pet. Do not feed. Do not attempt to converse with."`,
    },
    "39": {
      id: 39,
      name: "Humane pesticides",
      cost: { cookies: 550_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Made by people, for people, from people and ready to unleash some righteous scorching pain on those pesky insects that so deserve it."`,
    },
    "40": {
      id: 40,
      name: "Barnstars",

      cost: { cookies: 550_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Ah, yes. These help quite a bit. Somehow."`,
    },
    "41": {
      id: 41,
      name: "Lindworms",
      cost: { cookies: 550_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "You have to import these from far up north, but they really help areate the soil!"`,
    },
    "42": {
      id: 42,
      name: "Global seed vault",
      cost: { cookies: 550_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "An enormous genetic repository that could outlive an apocalypse. Guarantees the survival of your empire, or at the very least its agricultural components, should civilization fall. Which should be any day now."`,
    },
    "43": {
      id: 43,
      name: "Reverse-veganism",
      cost: { cookies: 550_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Plants aren't for eating, plants are for exploitative agriculture and astronomical profit margins!"`,
    },
    "44": {
      id: 44,
      name: "Cookie mulch",
      cost: { cookies: 550_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Grinding surplus cookies into paste that you then spread onto your fields enables a strange feedback loop in the quality of your cookie crops. Cookie feeding on cookie should be an abomination, but then why does it taste so good?"`,
    },
    "45": {
      id: 45,
      name: "Self-driving tractors",
      cost: {
        cookies: 550_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "farm",
      description: `Farms are twice as efficient.
      "Embarked AI lets your field vehicles sow and harvest cookie crops at any time of the day or night, and with so few human casualties, too!"`,
    },
  };
  public farmUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.farmUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 1100 },
      structureResourceGeneration: { cookies: 8 },
      structureResourceGenerationDefault: { cookies: 8 },

      structureCostDefault: { cookies: 1100 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.farmUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.farmUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.farmUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.farmUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.farmUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}
class Mine extends Structure {
  public farmUpgrades1: { [key: string]: UpgradeType } = {
    "46": {
      id: 46,
      name: "Sugar gas",
      cost: { cookies: 120_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "A pink, volatile gas, found in the depths of some chocolate caves."`,
    },
    "47": {
      id: 47,
      name: "Megadrill",
      cost: { cookies: 600_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "You're in deep."`,
    },
    "48": {
      id: 48,
      name: "Ultradrill",
      cost: { cookies: 6_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Finally caved in?"`,
    },
    "49": {
      id: 49,
      name: "Ultimadrill",
      cost: { cookies: 600_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Pierce the heavens, etc."`,
    },
    "50": {
      id: 50,
      name: "H-bomb mining",
      cost: { cookies: 60_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Questionable efficiency, but spectacular nonetheless."`,
    },
    "51": {
      id: 51,
      name: "Coreforge",
      cost: { cookies: 6_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "You've finally dug a tunnel down to the Earth's core. It's pretty warm down here."`,
    },
    "52": {
      id: 52,
      name: "Planetsplitters",
      cost: { cookies: 6_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "These new state-of-the-art excavators have been tested on Merula, Globort and Flwanza VI, among other distant planets which have been curiously quiet lately."`,
    },
    "53": {
      id: 53,
      name: "Canola oil wells",
      cost: { cookies: 6_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "A previously untapped resource, canola oil permeates the underground olifers which grant it its particular taste and lucrative properties."`,
    },
    "54": {
      id: 54,
      name: "Mole people",
      cost: { cookies: 6_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Engineered from real human beings within your very labs, these sturdy little folks have a knack for finding the tastiest underground minerals in conditions that more expensive machinery probably wouldn't survive."`,
    },
    "55": {
      id: 55,
      name: "Mine canaries",
      cost: { cookies: 6_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "These aren't used for anything freaky! The miners just enjoy having a pet or two down there."`,
    },
    "56": {
      id: 56,
      name: "Bore again",
      cost: { cookies: 6_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "After extracting so much sediment for so long, you've formed some veritable mountains of your own from the accumulated piles of rock and dirt. Time to dig through those and see if you find anything fun!"`,
    },
    "57": {
      id: 57,
      name: "Air mining",
      cost: { cookies: 6_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "You've dug your drills through just about every solid surface you could find. But did you know recent advances have revealed untold riches hiding within non-solid surfaces too?"`,
    },
    "58": {
      id: 58,
      name: "Caramel alloys",
      cost: { cookies: 6_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Your geologists have isolated a family of once-overlooked sugary ores that, when combined, may be turned into even more cookie ingredients. Your millions of miles of previously useless tunnels probably house insane amounts of the stuff!"`,
    },
    "59": {
      id: 59,
      name: "Delicious mineralogy",
      cost: { cookies: 6_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "Stratum after stratum, you've extracted strange new minerals heretofore unknown to geology. Ushering a new era of materials research, your scientists have been able to identify every new element your mines have discovered, including whatever those things are in the upgrade tier names."`,
    },
    "60": {
      id: 60,
      name: "Mineshaft supports",
      cost: { cookies: 6_000_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "mine",
      description: `Mines are twice as efficient.
      "You were rather skeptical about installing such embarrassingly low-tech implements, but limiting the number of daily cave-ins really does help with that annoying employee turnover!"`,
    },
  };
  public mineUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.farmUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 12_000 },
      structureResourceGeneration: { cookies: 47 },
      structureResourceGenerationDefault: { cookies: 47 },

      structureCostDefault: { cookies: 12_000 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.mineUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.mineUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.mineUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.mineUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.mineUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

class Factory extends Structure {
  public FactoryUpgrades1: { [key: string]: UpgradeType } = {
    "61": {
      id: 61,
      name: "Sturdier conveyor belts",
      cost: { cookies: 1_300_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "62": {
      id: 62,
      name: "Child labor",
      cost: { cookies: 6_500_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "63": {
      id: 63,
      name: "Sweatshop",
      cost: { cookies: 65_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "64": {
      id: 64,
      name: "Radium reactors",
      cost: { cookies: 6_500_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "65": {
      id: 65,
      name: "Recombobulators",
      cost: { cookies: 650_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "66": {
      id: 66,
      name: "Deep-bake process",
      cost: { cookies: 65_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "67": {
      id: 67,
      name: "Cyborg workforce",
      cost: { cookies: 65_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "68": {
      id: 68,
      name: "78-hour days",
      cost: { cookies: 65_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "69": {
      id: 69,
      name: "Machine learning",
      cost: { cookies: 65_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "70": {
      id: 70,
      name: "Brownie point system",
      cost: { cookies: 65_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "71": {
      id: 71,
      name: "Volunteer interns",
      cost: { cookies: 65_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "72": {
      id: 72,
      name: "Behavioral reframing",
      cost: { cookies: 65_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "73": {
      id: 73,
      name: "The Infinity Engine",
      cost: { cookies: 65_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "74": {
      id: 74,
      name: "N-dimensional assembly lines",
      cost: { cookies: 65_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
    "75": {
      id: 75,
      name: "Universal automation",
      cost: { cookies: 65_000_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "factory",
      description: `Factories are twice as efficient.`,
    },
  };
  public factoryUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.FactoryUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 130_000 },
      structureResourceGeneration: { cookies: 260 },
      structureResourceGenerationDefault: { cookies: 260 },

      structureCostDefault: { cookies: 130_000 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.factoryUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.factoryUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.factoryUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.factoryUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.factoryUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

class Bank extends Structure {
  public BankUpgrades1: { [key: string]: UpgradeType } = {
    "76": {
      id: 76,
      name: "Taller tellers",
      cost: { cookies: 14_000_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "77": {
      id: 77,
      name: "Scissor-resistant credit cards",
      cost: { cookies: 70_000_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "78": {
      id: 78,
      name: "Acid-proof vaults",
      cost: { cookies: 700_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "79": {
      id: 79,
      name: "Chocolate coins",
      cost: { cookies: 70_000_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "80": {
      id: 80,
      name: "Exponential interest rates",
      cost: { cookies: 7_000_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "81": {
      id: 81,
      name: "Financial zen",
      cost: { cookies: 700_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "82": {
      id: 82,
      name: "Way of the wallet",
      cost: { cookies: 700_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "83": {
      id: 83,
      name: "The stuff rationale",
      cost: { cookies: 700_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "84": {
      id: 84,
      name: "Edible money",
      cost: { cookies: 700_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "85": {
      id: 85,
      name: "Grand supercycles",
      cost: { cookies: 700_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "86": {
      id: 86,
      name: "Rules of acquisition",
      cost: { cookies: 700_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "87": {
      id: 87,
      name: "Altruistic loop",
      cost: { cookies: 700_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "88": {
      id: 88,
      name: "Diminishing tax returns",
      cost: { cookies: 700_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "89": {
      id: 89,
      name: "The 1%",
      cost: { cookies: 700_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
    "90": {
      id: 90,
      name: "Financial recursion",
      cost: {
        cookies: 700_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "bank",
      description: `Banks are twice as efficient.`,
    },
  };
  public bankUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.BankUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 1_400_000 },
      structureResourceGeneration: { cookies: 1_400 },
      structureResourceGenerationDefault: { cookies: 1_400 },

      structureCostDefault: { cookies: 1_400_000 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.bankUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.bankUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.bankUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.bankUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.bankUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

class Temple extends Structure {
  public templeUpgrades1: { [key: string]: UpgradeType } = {
    "91": {
      id: 91,
      name: "Golden idols",
      cost: { cookies: 200_000_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "92": {
      id: 92,
      name: "Sacrifices",
      cost: { cookies: 1_000_000_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "93": {
      id: 93,
      name: "Delicious blessing",
      cost: { cookies: 10_000_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "94": {
      id: 94,
      name: "Sun festival",
      cost: { cookies: 1_000_000_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "95": {
      id: 95,
      name: "Enlarged pantheon",
      cost: { cookies: 100_000_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "96": {
      id: 96,
      name: "Great Baker in the sky",
      cost: { cookies: 10_000_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "97": {
      id: 97,
      name: "Creation myth",
      cost: { cookies: 10_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "98": {
      id: 98,
      name: "Theocracy",
      cost: { cookies: 10_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "99": {
      id: 99,
      name: "Sick rap prayers",
      cost: { cookies: 10_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "100": {
      id: 100,
      name: "Psalm-reading",
      cost: { cookies: 10_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "101": {
      id: 101,
      name: "War of the gods",
      cost: { cookies: 100_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "102": {
      id: 102,
      name: "A novel idea",
      cost: { cookies: 1_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "103": {
      id: 103,
      name: "Apparitions",
      cost: { cookies: 10_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "104": {
      id: 104,
      name: "Negatheism",
      cost: {
        cookies: 100_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
    "105": {
      id: 105,
      name: " Temple Traps",
      cost: {
        cookies: 1_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "temple",
      description: `Temples are twice as efficient.`,
    },
  };
  public templeUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.templeUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 20_000_000 },
      structureResourceGeneration: { cookies: 7_800 },
      structureResourceGenerationDefault: { cookies: 7_800 },

      structureCostDefault: { cookies: 20_000_000 },
    });
    this.game = game;
  }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.templeUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.templeUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.templeUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.templeUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.templeUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

export class WizardTower extends Structure {
  public wizardTowerUpgrades1: { [key: string]: UpgradeType } = {
    "106": {
      id: 106,
      name: "Pointier hats",
      cost: { cookies: 3_300_000_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "107": {
      id: 107,
      name: "Beardlier beards",
      cost: { cookies: 16_500_000_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "108": {
      id: 108,
      name: "Ancient grimoires",
      cost: { cookies: 165_000_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "109": {
      id: 109,
      name: "Kitchen curses",
      cost: { cookies: 16_500_000_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "110": {
      id: 110,
      name: "School of sorcery",
      cost: { cookies: 1_650_000_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "111": {
      id: 111,
      name: "Dark formulas",
      cost: { cookies: 165_000_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "112": {
      id: 112,
      name: "Cookiemancy",
      cost: { cookies: 165_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "113": {
      id: 113,
      name: "Rabbit trick",
      cost: { cookies: 165_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "114": {
      id: 114,
      name: "Deluxe tailored wands",
      cost: { cookies: 165_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "115": {
      id: 115,
      name: "Immobile spellcasting",
      cost: { cookies: 165_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "116": {
      id: 116,
      name: "Electricity",
      cost: { cookies: 165_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "117": {
      id: 117,
      name: "Spelling bees",
      cost: { cookies: 165_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "118": {
      id: 118,
      name: "Wizzaaaaaard wands",
      cost: { cookies: 165_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "119": {
      id: 119,
      name: "Hexes and curses",
      cost: {
        cookies: 165_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
    "120": {
      id: 120,
      name: "Pointier hats",
      cost: {
        cookies: 165_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "wizardTower",
      description: `Wizard towers are twice as efficient.`,
    },
  };
  public WizardTowerUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.wizardTowerUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 330_000_000 },
      structureResourceGeneration: { cookies: 44_800 },
      structureResourceGenerationDefault: { cookies: 44_800 },

      structureCostDefault: { cookies: 330_000_000 },
    });
    this.game = game;
  }
  // public buyBuilding(amount: number = 1): void {
  //   this.increaseStructure(this.game.resource, amount);
  //   this.calculateStructureResourceGeneration1();
  // }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.WizardTowerUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.WizardTowerUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.WizardTowerUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.WizardTowerUpgrades.get(
      id.toString()
    )?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.WizardTowerUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}

export class Shipment extends Structure {
  public shipmentUpgrades1: { [key: string]: UpgradeType } = {
    "121": {
      id: 121,
      name: "Vanilla nebulae",
      cost: { cookies: 51_000_000_000 },
      multiplier: 2,
      requirement: 1,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "122": {
      id: 122,
      name: "Wormholes",
      cost: { cookies: 255_000_000_000 },
      multiplier: 2,
      requirement: 5,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "123": {
      id: 123,
      name: "Frequent flyer",
      cost: { cookies: 2_550_000_000_000 },
      multiplier: 2,
      requirement: 25,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "124": {
      id: 124,
      name: "Warp drive",
      cost: { cookies: 255_000_000_000_000 },
      multiplier: 2,
      requirement: 50,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "125": {
      id: 125,
      name: "Chocolate monoliths",
      cost: { cookies: 25_500_000_000_000_000 },
      multiplier: 2,
      requirement: 100,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "126": {
      id: 126,
      name: "Generation ship",
      cost: { cookies: 2_550_000_000_000_000_000 },
      multiplier: 2,
      requirement: 150,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    "127": {
      id: 127,
      name: "Dyson sphere",
      cost: { cookies: 2_550_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 200,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    128: {
      id: 128,
      name: "The final frontier",
      cost: { cookies: 2_550_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 250,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    129: {
      id: 129,
      name: "Autopilot",
      cost: { cookies: 2_550_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 300,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    130: {
      id: 130,
      name: "Restaurants at the end of the universe",
      cost: { cookies: 2_550_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 350,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    131: {
      id: 131,
      name: "Universal alphabet",
      cost: { cookies: 2_550_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 400,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    132: {
      id: 132,
      name: "Ancient tablet",
      cost: { cookies: 2_550_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 450,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    133: {
      id: 133,
      name: "Insane oatling workers",
      cost: { cookies: 2_550_000_000_000_000_000_000_000_000_000_000_000_000 },
      multiplier: 2,
      requirement: 500,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    134: {
      id: 134,
      name: "Soul bond",
      cost: {
        cookies: 2_550_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 550,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
    135: {
      id: 135,
      name: "Flux capacitors",
      cost: {
        cookies: 2_550_000_000_000_000_000_000_000_000_000_000_000_000_000_000,
      },
      multiplier: 2,
      requirement: 600,
      acquired: false,
      type: "shipment",
      description: `Shipments are twice as efficient.`,
    },
  };
  public shipmentUpgrades: Map<string, UpgradeType> = new Map(
    Object.entries(this.shipmentUpgrades1)
  );
  private game: Clicker;
  constructor(game: Clicker) {
    super({
      structure: 0,
      structureCost: { cookies: 5_100_000_000 },
      structureResourceGeneration: { cookies: 260_000 },
      structureResourceGenerationDefault: { cookies: 260_000 },

      structureCostDefault: { cookies: 5_100_000_000 },
    });
    this.game = game;
  }
  // public buyBuilding(amount: number = 1): void {
  //   this.increaseStructure(this.game.resource, amount);
  //   this.calculateStructureResourceGeneration1();
  // }
  public getUpgradesInRange(): UpgradeType[] {
    const upgrades: UpgradeType[] = [];
    this.shipmentUpgrades.forEach((upgrade) => {
      if (
        upgrade.requirement <= this.getStructureAmount() &&
        !upgrade.acquired
      ) {
        upgrades.push(upgrade);
      }
    });
    return upgrades;
  }
  public buyUpgradeLevel(cookies: Resource, id: number): void {
    const upgrade = this.shipmentUpgrades.get(id.toString());
    if (!upgrade) return;
    if (!this.canBuyStructureUpgrade(cookies, id)) return;
    cookies.cookies -= upgrade.cost.cookies;
    upgrade.acquired = true;
    this.calculateStructureResourceGeneration1();
    this.game.ClickCalculateResourceGeneration();
  }
  public calculateStructureResourceGeneration1(): void {
    this.structureResourceGeneration.cookies =
      this.structureResourceGenerationDefault.cookies;
    this.shipmentUpgrades.forEach((value, key) => {
      if (value.acquired) {
        this.structureResourceGeneration.cookies *= value.multiplier;
      }
    });
  }
  public getStructureUpgradeCost(id: number): string {
    return this.shipmentUpgrades.get(id.toString())?.cost.cookies.toString()!;
  }
  public canBuyStructureUpgrade(cookies: Resource, id: number): boolean {
    const nextUpgrade = this.shipmentUpgrades.get(id.toString());
    if (!nextUpgrade) {
      return false;
    }

    if (
      cookies.cookies >= nextUpgrade.cost.cookies &&
      this.getStructureAmount() >= nextUpgrade.requirement
    ) {
      return true;
    }
    return false;
  }
}
